# Generated by Django 4.2.30 on 2026-05-13 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('employers', '0002_rename_employerprofile_employer_and_align_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checklist_responses', models.JSONField(blank=True, default=dict)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('enforcement_action', models.CharField(choices=[('none', 'None'), ('advisory', 'Advisory'), ('warning', 'Warning'), ('compliance_notice', 'Compliance Notice'), ('follow_up_required', 'Follow Up Required'), ('sanction_recommended', 'Sanction Recommended'), ('escalated_to_state', 'Escalated To State')], db_index=True, default='none', max_length=32)),
                ('findings', models.TextField(blank=True)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('closed', 'Closed')], db_index=True, default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='employers.employer')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCertificateScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(db_index=True, max_length=64)),
                ('result', models.CharField(db_index=True, max_length=32)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_scans', to='certificates.certificate')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_scans', to='inspections.inspection')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['inspection'], name='inspections_inspect_13f973_idx'), models.Index(fields=['certificate_number'], name='inspections_certifi_950a30_idx'), models.Index(fields=['result'], name='inspections_result_162d45_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspector'], name='inspections_inspect_935cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['employer'], name='inspections_employe_4320da_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_date'], name='inspections_inspect_3cc2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['enforcement_action'], name='inspections_enforce_1083bc_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspections_status_094ca4_idx'),
        ),
    ]
