# Generated by Django 4.2.30 on 2026-05-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationunit_and_more'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='organizations.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['branch'], name='inspections_branch__08b854_idx'),
        ),
    ]
