# Generated by Django 4.2.30 on 2026-05-15 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0002_inspection_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('employer_response_submitted', 'Employer Response Submitted'), ('closed', 'Closed')], db_index=True, default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('acknowledge', 'Acknowledge'), ('corrective_action', 'Corrective Action'), ('evidence', 'Evidence'), ('comment', 'Comment')], db_index=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('evidence_file_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_responses', to='inspections.inspection')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['inspection'], name='inspections_inspect_d1a0d2_idx'), models.Index(fields=['submitted_by'], name='inspections_submitt_b08408_idx'), models.Index(fields=['response_type'], name='inspections_respons_534b58_idx'), models.Index(fields=['submitted_at'], name='inspections_submitt_685e3e_idx')],
            },
        ),
    ]
