# Generated by Django 4.2.30 on 2026-05-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0003_alter_inspection_status_inspectionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('routine', 'Routine Inspection'), ('follow_up', 'Follow-Up Inspection'), ('complaint_based', 'Complaint-Based Inspection'), ('certificate_sweep', 'Certificate Verification Sweep'), ('illness_risk', 'Illness / Public Health Risk Inspection'), ('facility_linked', 'Facility-Linked Verification')], db_index=True, default='routine', max_length=80),
        ),
        migrations.AddField(
            model_name='inspection',
            name='linked_complaint_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='linked_illness_report_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_inspections', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='supervising_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('returned_for_correction', 'Returned for Correction'), ('notice_issued', 'Notice Issued'), ('corrective_action_pending', 'Corrective Action Pending'), ('corrective_action_submitted', 'Corrective Action Submitted'), ('follow_up_required', 'Follow-Up Required'), ('follow_up_scheduled', 'Follow-Up Scheduled'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['reference'], name='inspections_referen_c5c697_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['assigned_by'], name='inspections_assigne_c6f880_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_type'], name='inspections_inspect_b60ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['priority'], name='inspections_priorit_4f3cbe_idx'),
        ),
    ]
