# Generated by Django 4.2.30 on 2026-05-25 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspection_assigned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('food_handler_certification', 'A. Food Handler Certification'), ('fitness_exclusion_compliance', 'B. Fitness and Exclusion Compliance'), ('vaccination_compliance', 'C. Vaccination Compliance'), ('employer_records', 'D. Employer Records'), ('hygiene_food_safety', 'E. Hygiene and Food Safety Practices'), ('certificate_authenticity', 'F. Certificate Authenticity'), ('corrective_action_compliance', 'G. Corrective Action Compliance')], db_index=True, max_length=50)),
                ('question', models.TextField()),
                ('severity_if_failed', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='major', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order'],
                'indexes': [models.Index(fields=['category'], name='inspections_categor_56f3fe_idx'), models.Index(fields=['is_active'], name='inspections_is_acti_138b96_idx')],
            },
        ),
    ]
