# Generated by Django 4.2.30 on 2026-05-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_handlers', '0004_foodhandlerprofile_business_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0005_certificatetemplate_certificate_template_and_more'),
        ('inspections', '0005_inspectionchecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('food_handler_certification', 'A. Food Handler Certification'), ('fitness_exclusion_compliance', 'B. Fitness and Exclusion Compliance'), ('vaccination_compliance', 'C. Vaccination Compliance'), ('employer_records', 'D. Employer Records'), ('hygiene_food_safety', 'E. Hygiene and Food Safety Practices'), ('certificate_authenticity', 'F. Certificate Authenticity'), ('corrective_action_compliance', 'G. Corrective Action Compliance')], max_length=100)),
                ('finding_type', models.CharField(choices=[('compliance_confirmed', 'Compliance Confirmed'), ('minor_non_compliance', 'Minor Non-Compliance'), ('major_non_compliance', 'Major Non-Compliance'), ('critical_non_compliance', 'Critical Non-Compliance'), ('suspicious_certificate', 'Suspicious Certificate'), ('public_health_risk', 'Public Health Risk'), ('documentation_gap', 'Documentation Gap'), ('repeat_violation', 'Repeat Violation')], default='minor_non_compliance', max_length=100)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=50)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('notice_issued', 'Notice Issued'), ('corrective_action_pending', 'Corrective Action Pending'), ('corrected', 'Corrected'), ('not_corrected', 'Not Corrected'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=50)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_findings', to='certificates.certificate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_created', to=settings.AUTH_USER_MODEL)),
                ('food_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_findings', to='food_handlers.foodhandlerprofile')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_findings', to='inspections.inspection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('cert_screenshot', 'Certificate Screenshot'), ('signed_notice', 'Signed Notice'), ('employer_response_doc', 'Employer Response Document'), ('inspector_note', 'Inspector Note'), ('gps_location', 'GPS/Location Metadata')], default='photo', max_length=50)),
                ('file_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='inspections.inspectionfinding')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_entries', to='inspections.inspection')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n_a', 'Not Applicable'), ('not_observed', 'Not Observed'), ('needs_follow_up', 'Needs Follow-Up')], default='not_observed', max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_responses', to='inspections.inspectionchecklistitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_item_responses', to='inspections.inspection')),
            ],
            options={
                'ordering': ['checklist_item__category', 'checklist_item__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionfinding',
            index=models.Index(fields=['inspection'], name='inspections_inspect_8f3af8_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionfinding',
            index=models.Index(fields=['finding_type'], name='inspections_finding_e6b21b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionfinding',
            index=models.Index(fields=['severity'], name='inspections_severit_44ce2b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionfinding',
            index=models.Index(fields=['status'], name='inspections_status_a156d7_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionfinding',
            index=models.Index(fields=['food_handler'], name='inspections_food_ha_5e45cd_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionfinding',
            index=models.Index(fields=['certificate'], name='inspections_certifi_a1fe84_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionevidence',
            index=models.Index(fields=['inspection'], name='inspections_inspect_87219f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionevidence',
            index=models.Index(fields=['finding'], name='inspections_finding_602d86_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionevidence',
            index=models.Index(fields=['evidence_type'], name='inspections_evidenc_d733af_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklistresponse',
            index=models.Index(fields=['inspection'], name='inspections_inspect_f67f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklistresponse',
            index=models.Index(fields=['checklist_item'], name='inspections_checkli_f8386c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklistresponse',
            index=models.Index(fields=['response'], name='inspections_respons_bc5d6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionchecklistresponse',
            unique_together={('inspection', 'checklist_item')},
        ),
    ]
