# Generated by Django 4.2.30 on 2026-05-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employer_business_settings_and_notifications'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationunit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0006_inspectionfinding_inspectionevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnforcementNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('notice_type', models.CharField(choices=[('advisory', 'Advisory Notice'), ('warning', 'Warning Notice'), ('compliance', 'Compliance Notice'), ('corrective_action', 'Corrective Action Notice'), ('follow_up', 'Follow-Up Notice'), ('suspension_recommendation', 'Suspension Recommendation'), ('closure_recommendation', 'Closure Recommendation'), ('public_health_escalation', 'Public Health Escalation'), ('cert_review_recommendation', 'Certificate Review Recommendation'), ('facility_review_recommendation', 'Facility Review Recommendation')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('corrective_action_pending', 'Corrective Action Pending'), ('response_submitted', 'Response Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('follow_up_required', 'Follow-Up Required'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='draft', max_length=50)),
                ('description', models.TextField()),
                ('required_corrective_actions', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_notices', to='organizations.organizationunit')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enforcement_notices', to='employers.employer')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='inspections.inspection')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnforcementCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('awaiting_employer_response', 'Awaiting Employer Response'), ('follow_up_required', 'Follow-Up Required'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('summary', models.TextField()),
                ('escalated_to', models.CharField(blank=True, choices=[('inspectorate_coordinator', 'Inspectorate Coordinator'), ('state_admin', 'State Ministry Admin'), ('federal', 'Federal Ministry Oversight'), ('other_authority', 'Other Regulatory Body')], max_length=50)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_cases', to='organizations.organizationunit')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enforcement_cases', to='employers.employer')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_cases_opened', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enforcement_cases', to='locations.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_note', models.TextField()),
                ('action_taken', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('more_evidence_requested', 'More Evidence Requested')], default='submitted', max_length=50)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='inspections.enforcementnotice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enforcementnotice',
            index=models.Index(fields=['notice_reference'], name='inspections_notice__43d0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementnotice',
            index=models.Index(fields=['inspection'], name='inspections_inspect_4f41f3_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementnotice',
            index=models.Index(fields=['employer'], name='inspections_employe_d38ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementnotice',
            index=models.Index(fields=['notice_type'], name='inspections_notice__e5a26b_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementnotice',
            index=models.Index(fields=['status'], name='inspections_status_8baa48_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementnotice',
            index=models.Index(fields=['deadline'], name='inspections_deadlin_4ecf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementcase',
            index=models.Index(fields=['case_reference'], name='inspections_case_re_1ecf05_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementcase',
            index=models.Index(fields=['state'], name='inspections_state_i_9d1584_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementcase',
            index=models.Index(fields=['employer'], name='inspections_employe_1faea1_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementcase',
            index=models.Index(fields=['status'], name='inspections_status_eff1de_idx'),
        ),
        migrations.AddIndex(
            model_name='enforcementcase',
            index=models.Index(fields=['severity'], name='inspections_severit_02d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveactionresponse',
            index=models.Index(fields=['notice'], name='inspections_notice__39658e_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveactionresponse',
            index=models.Index(fields=['submitted_by'], name='inspections_submitt_64bf78_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveactionresponse',
            index=models.Index(fields=['status'], name='inspections_status_5498bd_idx'),
        ),
    ]
