# Generated by Django 4.2.30 on 2026-06-27 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_inspectionsettingspolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionsettingspolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inspectionsettingspolicy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
