# Generated by Django 4.2.30 on 2026-05-12 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_organization_address_organization_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_registration_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('establishment_category', models.CharField(choices=[('restaurant_cafe', 'Restaurants and cafes'), ('bakery', 'Bakeries and pastry shops'), ('abattoir_butcher', 'Abattoirs, slaughter slabs, and butcher shops'), ('grocery_supermarket', 'Grocery stores and supermarkets'), ('food_truck_street_vendor', 'Food trucks and street vendors'), ('catering', 'Catering services'), ('school_cafeteria', 'School cafeterias'), ('hospital_kitchen', 'Hospital kitchens'), ('bar_pub', 'Bars and pubs'), ('food_processing_plant', 'Food processing plants'), ('hotel_resort', 'Hotels and resorts'), ('corporate_dining', 'Corporate dining facilities'), ('food_market_stall', 'Food markets and stalls'), ('farm_feed_processing', 'Farms and livestock feed processing plants'), ('daycare', 'Daycare centres')], max_length=64)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_phone', models.CharField(max_length=32)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('ward', models.CharField(blank=True, max_length=120)),
                ('number_of_food_handlers', models.PositiveIntegerField(default=0)),
                ('compliance_status', models.CharField(choices=[('pending', 'Pending'), ('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non Compliant')], db_index=True, default='pending', max_length=32)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='trial', max_length=32)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='locations.lga')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employer_profile', to='organizations.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='locations.state')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='employers_e_state_i_81fb7b_idx'), models.Index(fields=['lga'], name='employers_e_lga_id_c01015_idx'), models.Index(fields=['compliance_status'], name='employers_e_complia_37e2c7_idx'), models.Index(fields=['subscription_status'], name='employers_e_subscri_b2f565_idx')],
            },
        ),
    ]
