# Generated by Django 4.2.30 on 2026-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_rename_employerprofile_employer_and_align_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
