# Generated by Django 4.2.30 on 2026-05-12 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_address_organization_email_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('diagnostic_centre', 'Diagnostic centre'), ('primary_health_centre', 'Primary health centre'), ('mobile_health_unit', 'Mobile health unit')], max_length=32)),
                ('ownership_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('mission', 'Mission'), ('ngo', 'NGO')], max_length=32)),
                ('license_number', models.CharField(db_index=True, max_length=120)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('accreditation_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('reaccreditation_due', 'Re-accreditation Due')], db_index=True, default='draft', max_length=32)),
                ('accreditation_start_date', models.DateField(blank=True, null=True)),
                ('accreditation_expiry_date', models.DateField(blank=True, null=True)),
                ('standard_assessment_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_medical_facilities', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_facilities', to='locations.lga')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_facility', to='organizations.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_facilities', to='locations.state')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityAccreditationApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('reaccreditation_due', 'Re-accreditation Due')], db_index=True, default='draft', max_length=32)),
                ('has_reporting_policy', models.BooleanField(default=False)),
                ('has_medical_records_computers', models.BooleanField(default=False)),
                ('has_computer_operators', models.BooleanField(default=False)),
                ('has_standard_forms', models.BooleanField(default=False)),
                ('has_laboratory_request_forms', models.BooleanField(default=False)),
                ('has_patient_files', models.BooleanField(default=False)),
                ('has_qr_certificate_capability', models.BooleanField(default=False)),
                ('has_internet_access', models.BooleanField(default=False)),
                ('has_trained_records_staff', models.BooleanField(default=False)),
                ('has_trained_clinical_staff', models.BooleanField(default=False)),
                ('has_trained_non_clinical_staff', models.BooleanField(default=False)),
                ('supporting_document', models.FileField(blank=True, upload_to='facility_accreditation/')),
                ('review_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_applications', to='facilities.medicalfacility')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_facility_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalfacility',
            index=models.Index(fields=['state'], name='facilities__state_i_a08c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfacility',
            index=models.Index(fields=['lga'], name='facilities__lga_id_dc169d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfacility',
            index=models.Index(fields=['accreditation_status'], name='facilities__accredi_f33c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfacility',
            index=models.Index(fields=['facility_type'], name='facilities__facilit_ade221_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityaccreditationapplication',
            index=models.Index(fields=['facility'], name='facilities__facilit_cb7a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityaccreditationapplication',
            index=models.Index(fields=['application_status'], name='facilities__applica_9a281e_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityaccreditationapplication',
            index=models.Index(fields=['submitted_at'], name='facilities__submitt_f3950d_idx'),
        ),
    ]
