# Generated by Django 4.2.30 on 2026-05-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_staff_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facilitydocument',
            new_name='facilities__facilit_22951e_idx',
            old_name='facilities__facilit_55cedd_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitydocument',
            new_name='facilities__accredi_5a2482_idx',
            old_name='facilities__accredi_01f7b6_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitydocument',
            new_name='facilities__documen_365773_idx',
            old_name='facilities__documen_8e32b4_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitydocument',
            new_name='facilities__status_931409_idx',
            old_name='facilities__status_5d924c_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitystaffprofile',
            new_name='facilities__facilit_bc249d_idx',
            old_name='facilities__facilit_9f59e7_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitystaffprofile',
            new_name='facilities__departm_966049_idx',
            old_name='facilities__departm_e5b539_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitystaffprofile',
            new_name='facilities__staff_t_bcbacd_idx',
            old_name='facilities__staff_t_45e5b6_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitystaffprofile',
            new_name='facilities__is_acti_834508_idx',
            old_name='facilities__is_acti_2d674b_idx',
        ),
    ]
