# Generated by Django 4.2.30 on 2026-05-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_organizationunit_unit_type'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryStaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry_type', models.CharField(choices=[('state', 'State Ministry'), ('federal', 'Federal Ministry')], db_index=True, max_length=16)),
                ('sub_role', models.CharField(choices=[('state_super_admin', 'State Ministry Super Admin'), ('food_safety_officer', 'Food Safety Directorate Officer'), ('certificate_verification_officer', 'Certificate Verification Officer'), ('facility_accreditation_officer', 'Facility Accreditation Officer'), ('policy_finance_officer', 'Policy and Finance Officer'), ('inspectorate_coordinator', 'Inspectorate Coordinator'), ('lga_officer', 'LGA Office Officer'), ('federal_super_admin', 'Federal Ministry Super Admin'), ('national_food_safety_officer', 'National Food Safety Programme Officer'), ('national_me_officer', 'National M&E Officer'), ('national_policy_officer', 'National Policy Officer'), ('national_finance_officer', 'National Finance/Oversight Officer'), ('federal_viewer', 'Federal Viewer')], db_index=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ministry_profiles', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_staff', to='locations.lga')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_staff', to='locations.state')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_staff', to='organizations.organizationunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
                'indexes': [models.Index(fields=['ministry_type'], name='ministries__ministr_c5cb27_idx'), models.Index(fields=['sub_role'], name='ministries__sub_rol_5791db_idx'), models.Index(fields=['state'], name='ministries__state_i_87a5a6_idx'), models.Index(fields=['lga'], name='ministries__lga_id_a546b9_idx'), models.Index(fields=['unit'], name='ministries__unit_id_92d807_idx'), models.Index(fields=['is_active'], name='ministries__is_acti_271914_idx')],
            },
        ),
    ]
