# Generated by Django 4.2.30 on 2026-05-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0003_federalstatequery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='federalstatequery',
            new_name='ministries__state_i_652e24_idx',
            old_name='ministries__state_i_07a9f7_idx',
        ),
        migrations.RenameIndex(
            model_name='federalstatequery',
            new_name='ministries__categor_c77222_idx',
            old_name='ministries__categor_568a9f_idx',
        ),
        migrations.RenameIndex(
            model_name='federalstatequery',
            new_name='ministries__priorit_07b82c_idx',
            old_name='ministries__priorit_7f75a8_idx',
        ),
        migrations.RenameIndex(
            model_name='federalstatequery',
            new_name='ministries__status_513085_idx',
            old_name='ministries__status_dde0bc_idx',
        ),
        migrations.RenameIndex(
            model_name='federalstatequery',
            new_name='ministries__created_dd00a4_idx',
            old_name='ministries__created_1c9ea6_idx',
        ),
        migrations.RenameIndex(
            model_name='statereport',
            new_name='ministries__state_i_a36f89_idx',
            old_name='ministries__state_i_6d2d53_idx',
        ),
        migrations.RenameIndex(
            model_name='statereport',
            new_name='ministries__report__268779_idx',
            old_name='ministries__report__a02e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='statereport',
            new_name='ministries__status_3f7640_idx',
            old_name='ministries__status_2f6fd7_idx',
        ),
        migrations.RenameIndex(
            model_name='statereport',
            new_name='ministries__reporti_9284f0_idx',
            old_name='ministries__reporti_97dc6a_idx',
        ),
    ]
