# Generated by Django 4.2.30 on 2026-06-30 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministries', '0004_rename_ministries__state_i_07a9f7_idx_ministries__state_i_652e24_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry_name', models.CharField(default='Federal Ministry of Health and Social Welfare', max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('programme_name', models.CharField(blank=True, max_length=255)),
                ('national_coordinator', models.CharField(blank=True, max_length=255)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('official_phone', models.CharField(blank=True, max_length=32)),
                ('logo_url', models.URLField(blank=True)),
                ('active_guideline_version', models.CharField(blank=True, default="National Guidelines for Food Handlers' Medical Test 2024", max_length=255)),
                ('reporting_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='quarterly', max_length=16)),
                ('central_portal_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_federal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
