# Generated by Django 4.2.30 on 2026-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0005_federalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('accepted', 'Accepted'), ('escalated', 'Escalated')], db_index=True, default='generated', max_length=16),
        ),
    ]
