# Generated by Django 4.2.30 on 2026-06-01 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationunit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('recipient_type', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('account', 'Account'), ('identity_verification', 'Identity Verification'), ('employer_management', 'Employer Management'), ('facility_accreditation', 'Facility Accreditation'), ('appointment', 'Appointment'), ('assessment', 'Assessment'), ('lab_workflow', 'Lab Workflow'), ('vaccination', 'Vaccination'), ('certificate', 'Certificate'), ('renewal', 'Renewal'), ('payments', 'Payments'), ('subscriptions', 'Subscriptions'), ('settlements', 'Settlements'), ('inspection', 'Inspection'), ('enforcement', 'Enforcement'), ('reports', 'Reports'), ('m_and_e', 'M&E'), ('data_quality', 'Data Quality'), ('security', 'Security'), ('system', 'System')], db_index=True, default='system', max_length=80)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='organizations.organization')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='organizations.organizationunit')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In App'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('sender_id', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=1)),
                ('rate_limit_per_minute', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority_order', 'name'],
                'indexes': [models.Index(fields=['channel'], name='notificatio_channel_7e62e5_idx'), models.Index(fields=['is_default'], name='notificatio_is_defa_a8bb3f_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_5fa870_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(db_index=True, max_length=150)),
                ('source_module', models.CharField(max_length=100)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_key'], name='notificatio_event_k_9e2f94_idx'), models.Index(fields=['source_module'], name='notificatio_source__36ad19_idx'), models.Index(fields=['processed'], name='notificatio_process_c30051_idx'), models.Index(fields=['created_at'], name='notificatio_created_07fd57_idx')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('account', 'Account'), ('identity_verification', 'Identity Verification'), ('employer_management', 'Employer Management'), ('facility_accreditation', 'Facility Accreditation'), ('appointment', 'Appointment'), ('assessment', 'Assessment'), ('lab_workflow', 'Lab Workflow'), ('vaccination', 'Vaccination'), ('certificate', 'Certificate'), ('renewal', 'Renewal'), ('payments', 'Payments'), ('subscriptions', 'Subscriptions'), ('settlements', 'Settlements'), ('inspection', 'Inspection'), ('enforcement', 'Enforcement'), ('reports', 'Reports'), ('m_and_e', 'M&E'), ('data_quality', 'Data Quality'), ('security', 'Security'), ('system', 'System')], max_length=80)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=50)),
                ('audience_type', models.CharField(max_length=100)),
                ('audience_filters', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=50)),
                ('estimated_recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_key', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('account', 'Account'), ('identity_verification', 'Identity Verification'), ('employer_management', 'Employer Management'), ('facility_accreditation', 'Facility Accreditation'), ('appointment', 'Appointment'), ('assessment', 'Assessment'), ('lab_workflow', 'Lab Workflow'), ('vaccination', 'Vaccination'), ('certificate', 'Certificate'), ('renewal', 'Renewal'), ('payments', 'Payments'), ('subscriptions', 'Subscriptions'), ('settlements', 'Settlements'), ('inspection', 'Inspection'), ('enforcement', 'Enforcement'), ('reports', 'Reports'), ('m_and_e', 'M&E'), ('data_quality', 'Data Quality'), ('security', 'Security'), ('system', 'System')], max_length=80)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In App'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('allowed_variables', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=20)),
                ('scope', models.CharField(choices=[('system', 'System'), ('national', 'National'), ('state', 'State')], default='system', max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_created', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to='locations.state')),
            ],
            options={
                'ordering': ['template_key', '-version'],
                'indexes': [models.Index(fields=['template_key'], name='notificatio_templat_8e899e_idx'), models.Index(fields=['category'], name='notificatio_categor_7eadfe_idx'), models.Index(fields=['channel'], name='notificatio_channel_ba807a_idx'), models.Index(fields=['status'], name='notificatio_status_609034_idx'), models.Index(fields=['scope', 'state'], name='notificatio_scope_30bece_idx')],
                'unique_together': {('template_key', 'channel', 'language', 'version')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('account', 'Account'), ('identity_verification', 'Identity Verification'), ('employer_management', 'Employer Management'), ('facility_accreditation', 'Facility Accreditation'), ('appointment', 'Appointment'), ('assessment', 'Assessment'), ('lab_workflow', 'Lab Workflow'), ('vaccination', 'Vaccination'), ('certificate', 'Certificate'), ('renewal', 'Renewal'), ('payments', 'Payments'), ('subscriptions', 'Subscriptions'), ('settlements', 'Settlements'), ('inspection', 'Inspection'), ('enforcement', 'Enforcement'), ('reports', 'Reports'), ('m_and_e', 'M&E'), ('data_quality', 'Data Quality'), ('security', 'Security'), ('system', 'System')], max_length=80)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In App'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_0299fd_idx'), models.Index(fields=['category'], name='notificatio_categor_930031_idx'), models.Index(fields=['channel'], name='notificatio_channel_e749a1_idx')],
                'unique_together': {('user', 'category', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In App'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('rejected', 'Rejected'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('read', 'Read'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification'], name='notificatio_notific_228f31_idx'), models.Index(fields=['channel'], name='notificatio_channel_927dd0_idx'), models.Index(fields=['status'], name='notificatio_status_533452_idx'), models.Index(fields=['provider'], name='notificatio_provide_f01098_idx'), models.Index(fields=['next_retry_at'], name='notificatio_next_re_bf42b2_idx'), models.Index(fields=['created_at'], name='notificatio_created_f0c306_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category'], name='notificatio_categor_fd561f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization'], name='notificatio_organiz_db32ee_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_unit'], name='notificatio_organiz_5ea8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['category'], name='notificatio_categor_998db6_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['status'], name='notificatio_status_f8b23c_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['created_by'], name='notificatio_created_df2594_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['created_at'], name='notificatio_created_ac38f5_idx'),
        ),
    ]
