# Generated by Django 4.2.30 on 2026-05-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='metadata',
            new_name='context_data',
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('certificate_expiry_reminder', 'Certificate Expiry Reminder'), ('certificate_renewal', 'Certificate Renewal'), ('vaccination_due', 'Vaccination Due'), ('accreditation_expiry', 'Accreditation Expiry'), ('illness_reported', 'Illness Reported'), ('return_to_work_cleared', 'Return To Work Cleared'), ('subscription_expiry', 'Subscription Expiry'), ('settlement_processed', 'Settlement Processed'), ('inspection_assigned', 'Inspection Assigned'), ('compliance_notice', 'Compliance Notice'), ('system_announcement', 'System Announcement'), ('other', 'Other')], db_index=True, default='other', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='template_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In App')], default='in_app', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
    ]
