# Generated by Django 4.2.30 on 2026-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_f07ec4_idx'),
        ),
    ]
