# Generated by Django 4.2.30 on 2026-05-13 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatePolicyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_state_certificate_validation', models.BooleanField(default=True)),
                ('certificate_validity_months', models.PositiveIntegerField(default=6)),
                ('typhoid_validity_years', models.PositiveIntegerField(default=3)),
                ('hepatitis_a_second_dose_months', models.PositiveIntegerField(default=6)),
                ('auto_renewal_reminder_days', models.JSONField(default=list)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_config', to='locations.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_state_policy_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='policy_stat_state_i_21ca4b_idx')],
            },
        ),
    ]
