# Generated by Django 4.2.30 on 2026-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_alter_nationalpolicyconfig_certificate_validity_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalpolicyconfig',
            name='state_certificate_template_overrides_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
