PERMISSIONS = [
    {"code": "organization.view", "name": "View organizations", "module": "organization"},
    {"code": "organization.create", "name": "Create organizations", "module": "organization", "is_sensitive": True},
    {"code": "organization.update", "name": "Update organizations", "module": "organization", "is_sensitive": True},
    {"code": "organization.suspend", "name": "Suspend organizations", "module": "organization", "is_sensitive": True},
    {"code": "unit.view", "name": "View units", "module": "unit"},
    {"code": "unit.create", "name": "Create units", "module": "unit"},
    {"code": "unit.update", "name": "Update units", "module": "unit"},
    {"code": "unit.deactivate", "name": "Deactivate units", "module": "unit", "is_sensitive": True},
    {"code": "unit.assign_user", "name": "Assign users to units", "module": "unit", "is_sensitive": True},
    {"code": "unit.view_members", "name": "View unit members", "module": "unit"},
    {"code": "user.view", "name": "View users", "module": "user"},
    {"code": "user.invite", "name": "Invite users", "module": "user"},
    {"code": "user.update", "name": "Update users", "module": "user"},
    {"code": "user.suspend", "name": "Suspend users", "module": "user", "is_sensitive": True},
    {"code": "user.reactivate", "name": "Reactivate users", "module": "user", "is_sensitive": True},
    {"code": "user.remove", "name": "Remove users", "module": "user", "is_sensitive": True},
    {"code": "invite.view", "name": "View invites", "module": "invite"},
    {"code": "invite.create", "name": "Create invites", "module": "invite"},
    {"code": "invite.resend", "name": "Resend invites", "module": "invite"},
    {"code": "invite.revoke", "name": "Revoke invites", "module": "invite", "is_sensitive": True},
    {"code": "role.view", "name": "View roles", "module": "role"},
    {"code": "role.assign", "name": "Assign roles", "module": "role", "is_sensitive": True},
    {"code": "role.create_custom", "name": "Create custom roles", "module": "role", "is_sensitive": True},
    {"code": "role.update_custom", "name": "Update custom roles", "module": "role", "is_sensitive": True},
    {"code": "permission.view", "name": "View permissions", "module": "permission"},
    {"code": "permission.override", "name": "Override permissions", "module": "permission", "is_sensitive": True},
    {"code": "employer.manage_branch", "name": "Manage employer branches", "module": "employer"},
    {"code": "employer.view_compliance", "name": "View employer compliance", "module": "employer"},
    {"code": "facility.manage_department", "name": "Manage facility departments", "module": "facility"},
    {"code": "facility.invite_staff", "name": "Invite facility staff", "module": "facility"},
    {"code": "facility.accredit", "name": "Manage facility accreditation", "module": "facility", "is_sensitive": True},
    {"code": "facility.profile.view", "name": "View facility profile", "module": "facility"},
    {"code": "facility.profile.edit", "name": "Edit facility profile", "module": "facility", "is_sensitive": True},
    {"code": "facility.team.invite", "name": "Invite facility team members", "module": "facility", "is_sensitive": True},
    {"code": "facility.team.remove", "name": "Remove facility team members", "module": "facility", "is_sensitive": True},
    {"code": "facility.roles.create", "name": "Create facility roles", "module": "facility", "is_sensitive": True},
    {"code": "facility.roles.edit", "name": "Edit facility roles", "module": "facility", "is_sensitive": True},
    {"code": "facility.roles.assign_permissions", "name": "Assign facility role permissions", "module": "facility", "is_sensitive": True},
    {"code": "appointments.view", "name": "View appointments", "module": "appointment"},
    {"code": "appointments.confirm", "name": "Confirm appointments", "module": "appointment", "is_sensitive": True},
    {"code": "appointments.cancel", "name": "Cancel appointments", "module": "appointment", "is_sensitive": True},
    {"code": "assessment.check_in", "name": "Check in food handlers", "module": "assessment"},
    {"code": "assessment.verify_identity", "name": "Verify food handler identity", "module": "assessment"},
    {"code": "declaration.view", "name": "View health declarations", "module": "declaration", "is_sensitive": True},
    {"code": "declaration.validate", "name": "Validate health declarations", "module": "declaration", "is_sensitive": True},
    {"code": "declaration.request_correction", "name": "Request declaration correction", "module": "declaration", "is_sensitive": True},
    {"code": "physical_exam.create", "name": "Create physical examinations", "module": "physical_exam", "is_sensitive": True},
    {"code": "lab_requests.view", "name": "View lab requests", "module": "lab"},
    {"code": "lab_results.create", "name": "Create lab results", "module": "lab", "is_sensitive": True},
    {"code": "lab_results.submit", "name": "Submit lab results", "module": "lab", "is_sensitive": True},
    {"code": "lab_results.review", "name": "Review lab results", "module": "lab", "is_sensitive": True},
    {"code": "doctor_review.view", "name": "View doctor review workspace", "module": "doctor_review", "is_sensitive": True},
    {"code": "doctor_review.final_decision", "name": "Confirm doctor final decision", "module": "doctor_review", "is_sensitive": True},
    {"code": "certificates.view", "name": "View certificates", "module": "certificate"},
    {"code": "unfit_reports.view", "name": "View temporary unfit reports", "module": "report", "is_sensitive": True},
    {"code": "finance.view_payments", "name": "View facility payments", "module": "finance", "is_sensitive": True},
    {"code": "finance.confirm_payment", "name": "Confirm facility payments", "module": "finance", "is_sensitive": True},
    {"code": "compliance.view_dashboard", "name": "View compliance dashboard", "module": "compliance"},
    {"code": "audit_logs.view", "name": "View audit logs", "module": "audit", "is_sensitive": True},
    {"code": "certificate.verify", "name": "Verify certificates", "module": "certificate"},
    {"code": "certificate.validate", "name": "Validate certificates", "module": "certificate", "is_sensitive": True},
    {"code": "inspection.conduct", "name": "Conduct inspections", "module": "inspection"},
    {"code": "inspection.assign", "name": "Assign inspections", "module": "inspection", "is_sensitive": True},
    {"code": "state.fee.manage", "name": "Manage state fee schedules", "module": "state_finance", "is_sensitive": True},
    {"code": "state.report.manage", "name": "Generate and submit state reports", "module": "state_reports", "is_sensitive": True},
    {"code": "medical_data.restricted_view", "name": "View restricted medical oversight data", "module": "medical_data", "is_sensitive": True},
    {"code": "payment.view", "name": "View payments", "module": "payment"},
    {"code": "settlement.view", "name": "View settlements", "module": "settlement"},
    {"code": "report.export", "name": "Export reports", "module": "report", "is_sensitive": True},
    # --- Performance Indicators (KPI engine) ---
    {"code": "indicators.view_federal", "name": "View federal indicators", "module": "indicators"},
    {"code": "indicators.create_federal", "name": "Create federal indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.update_federal", "name": "Update federal indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.publish_federal", "name": "Publish federal indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.share_to_states", "name": "Share indicators with states", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.set_national_targets", "name": "Set national indicator targets", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.manage_thresholds", "name": "Manage indicator thresholds", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.view_cross_state_results", "name": "View cross-state indicator results", "module": "indicators"},
    {"code": "indicators.export_federal_results", "name": "Export federal indicator results", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.ai_use_federal", "name": "Use AI on federal indicators", "module": "indicators"},
    {"code": "indicators.view_state", "name": "View state indicators", "module": "indicators"},
    {"code": "indicators.create_state", "name": "Create state indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.update_state", "name": "Update state indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.adopt_federal", "name": "Adopt federal indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.clone_federal", "name": "Clone federal indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.set_state_targets", "name": "Set state indicator targets", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.manage_state_thresholds", "name": "Manage state indicator thresholds", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.view_state_results", "name": "View state indicator results", "module": "indicators"},
    {"code": "indicators.export_state_results", "name": "Export state indicator results", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.ai_use_state", "name": "Use AI on state indicators", "module": "indicators"},
    {"code": "indicators.view_employer", "name": "View employer indicators", "module": "indicators"},
    {"code": "indicators.view_branch_indicators", "name": "View branch indicators", "module": "indicators"},
    {"code": "indicators.export_employer_indicators", "name": "Export employer indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.ai_use_employer", "name": "Use AI on employer indicators", "module": "indicators"},
    {"code": "indicators.view_facility", "name": "View facility indicators", "module": "indicators"},
    {"code": "indicators.view_assessment_indicators", "name": "View assessment indicators", "module": "indicators"},
    {"code": "indicators.export_facility_indicators", "name": "Export facility indicators", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.ai_use_facility", "name": "Use AI on facility indicators", "module": "indicators"},
    {"code": "indicators.manage_system_defaults", "name": "Manage indicator system defaults", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.manage_dataset_registry", "name": "Manage indicator dataset registry", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.manage_formula_engine", "name": "Manage indicator formula engine", "module": "indicators", "is_sensitive": True},
    {"code": "indicators.view_all_audit_logs", "name": "View all indicator audit logs", "module": "indicators", "is_sensitive": True},
]


PERMISSION_CODES = {p["code"]: p["code"] for p in PERMISSIONS}
