PERMISSIONS = [
    {"code": "organization.view", "name": "View organizations", "module": "organization"},
    {"code": "organization.create", "name": "Create organizations", "module": "organization", "is_sensitive": True},
    {"code": "organization.update", "name": "Update organizations", "module": "organization", "is_sensitive": True},
    {"code": "organization.suspend", "name": "Suspend organizations", "module": "organization", "is_sensitive": True},
    {"code": "unit.view", "name": "View units", "module": "unit"},
    {"code": "unit.create", "name": "Create units", "module": "unit"},
    {"code": "unit.update", "name": "Update units", "module": "unit"},
    {"code": "unit.deactivate", "name": "Deactivate units", "module": "unit", "is_sensitive": True},
    {"code": "unit.assign_user", "name": "Assign users to units", "module": "unit", "is_sensitive": True},
    {"code": "unit.view_members", "name": "View unit members", "module": "unit"},
    {"code": "user.view", "name": "View users", "module": "user"},
    {"code": "user.invite", "name": "Invite users", "module": "user"},
    {"code": "user.update", "name": "Update users", "module": "user"},
    {"code": "user.suspend", "name": "Suspend users", "module": "user", "is_sensitive": True},
    {"code": "user.reactivate", "name": "Reactivate users", "module": "user", "is_sensitive": True},
    {"code": "user.remove", "name": "Remove users", "module": "user", "is_sensitive": True},
    {"code": "invite.view", "name": "View invites", "module": "invite"},
    {"code": "invite.create", "name": "Create invites", "module": "invite"},
    {"code": "invite.resend", "name": "Resend invites", "module": "invite"},
    {"code": "invite.revoke", "name": "Revoke invites", "module": "invite", "is_sensitive": True},
    {"code": "role.view", "name": "View roles", "module": "role"},
    {"code": "role.assign", "name": "Assign roles", "module": "role", "is_sensitive": True},
    {"code": "role.create_custom", "name": "Create custom roles", "module": "role", "is_sensitive": True},
    {"code": "role.update_custom", "name": "Update custom roles", "module": "role", "is_sensitive": True},
    {"code": "permission.view", "name": "View permissions", "module": "permission"},
    {"code": "permission.override", "name": "Override permissions", "module": "permission", "is_sensitive": True},
    {"code": "employer.manage_branch", "name": "Manage employer branches", "module": "employer"},
    {"code": "employer.view_compliance", "name": "View employer compliance", "module": "employer"},
    {"code": "facility.manage_department", "name": "Manage facility departments", "module": "facility"},
    {"code": "facility.invite_staff", "name": "Invite facility staff", "module": "facility"},
    {"code": "facility.accredit", "name": "Manage facility accreditation", "module": "facility", "is_sensitive": True},
    {"code": "certificate.verify", "name": "Verify certificates", "module": "certificate"},
    {"code": "certificate.validate", "name": "Validate certificates", "module": "certificate", "is_sensitive": True},
    {"code": "inspection.conduct", "name": "Conduct inspections", "module": "inspection"},
    {"code": "inspection.assign", "name": "Assign inspections", "module": "inspection", "is_sensitive": True},
    {"code": "payment.view", "name": "View payments", "module": "payment"},
    {"code": "settlement.view", "name": "View settlements", "module": "settlement"},
    {"code": "report.export", "name": "Export reports", "module": "report", "is_sensitive": True},
]


PERMISSION_CODES = {p["code"]: p["code"] for p in PERMISSIONS}
