# Generated by Django 4.2.30 on 2026-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('role_change', 'Role Change'), ('workflow_transition', 'Workflow Transition'), ('payment_event', 'Payment Event'), ('medical_record_access', 'Medical Record Access'), ('certificate_event', 'Certificate Event'), ('public_verification', 'Public Verification'), ('security_event', 'Security Event')], db_index=True, max_length=64),
        ),
    ]
