from django.urls import path

from apps.ministries.views import (
    FederalDashboardView,
    FederalAuditLogView,
    FederalCertificateDetailView,
    FederalCertificateRegistryView,
    FederalCertificateAnalyticsView,
    FederalCertificateFlagView,
    FederalDataQualityView,
    FederalEmployerRegistryView,
    FederalFinanceDashboardView,
    FederalFinanceRevenueByStateView,
    FederalFinanceSettlementListView,
    FederalFinanceSubscriptionsView,
    FederalFacilityRegistryView,
    FederalFoodHandlerSummaryView,
    FederalIndicatorsView,
    FederalPolicyView,
    FederalQueryCloseView,
    FederalQueryListCreateView,
    FederalQueryRespondView,
    FederalStatePerformanceView,
    FederalStateSummaryView,
    FederalStateOverrideView,
    StateDashboardView,
    StateFacilityApplicationApproveView,
    StateFacilityApplicationListView,
    StateFacilityApplicationRejectView,
    StateFacilityApplicationReinstateView,
    StateFacilityApplicationSuspendView,
    StateFacilityApproveView,
    StateFacilityListView,
    StateFacilityRejectView,
    StateFacilityReinstateView,
    StateFacilitySuspendView,
    StateInviteDetailView,
    StateInviteListCreateView,
    StateAssessmentFeeDetailView,
    StateAssessmentFeeListCreateView,
    StateCertificateValidationApproveView,
    StateCertificateValidationClarificationView,
    StateCertificateValidationDetailView,
    StateCertificateValidationListView,
    StateCertificateValidationRejectView,
    StateCertificateRegistryDetailView,
    StateCertificateAuditView,
    StateCertificateExportView,
    StateCertificateRegistryListView,
    StateCertificateReinstateView,
    StateCertificateReplaceView,
    StateCertificateRevokeView,
    StateCertificateSuspendView,
    StateEmployerMonitoringView,
    StateFoodHandlerMonitoringView,
    StateIllnessMonitoringView,
    StateInspectionCloseView,
    StateInspectionDetailView,
    StateInspectionListView,
    StateInspectionReviewView,
    StateReportGenerateView,
    StateReportListView,
    StateReportSubmitView,
    StateFinanceDashboardView,
    StateFinanceExportView,
    StateRefundListView,
    StateRevenueView,
    StateSettlementListView,
    StateUnitDetailView,
    StateUnitListCreateView,
    StateUserListView,
)


urlpatterns = [
    path("state/dashboard/", StateDashboardView.as_view(), name="state-dashboard"),
    path("state/units/", StateUnitListCreateView.as_view(), name="state-units"),
    path("state/units/<uuid:pk>/", StateUnitDetailView.as_view(), name="state-unit-detail"),
    path("state/users/", StateUserListView.as_view(), name="state-users"),
    path("state/invites/", StateInviteListCreateView.as_view(), name="state-invites"),
    path("state/invites/<uuid:pk>/", StateInviteDetailView.as_view(), name="state-invite-detail"),
    path("state/facilities/", StateFacilityListView.as_view(), name="state-facilities"),
    path("state/facilities/applications/", StateFacilityApplicationListView.as_view(), name="state-facility-applications"),
    path("state/facilities/applications/<uuid:pk>/approve/", StateFacilityApplicationApproveView.as_view(), name="state-facility-application-approve"),
    path("state/facilities/applications/<uuid:pk>/reject/", StateFacilityApplicationRejectView.as_view(), name="state-facility-application-reject"),
    path("state/facilities/applications/<uuid:pk>/suspend/", StateFacilityApplicationSuspendView.as_view(), name="state-facility-application-suspend"),
    path("state/facilities/applications/<uuid:pk>/reinstate/", StateFacilityApplicationReinstateView.as_view(), name="state-facility-application-reinstate"),
    path("state/facilities/<uuid:pk>/approve/", StateFacilityApproveView.as_view(), name="state-facility-approve"),
    path("state/facilities/<uuid:pk>/reject/", StateFacilityRejectView.as_view(), name="state-facility-reject"),
    path("state/facilities/<uuid:pk>/suspend/", StateFacilitySuspendView.as_view(), name="state-facility-suspend"),
    path("state/facilities/<uuid:pk>/reinstate/", StateFacilityReinstateView.as_view(), name="state-facility-reinstate"),
    path("state/fees/", StateAssessmentFeeListCreateView.as_view(), name="state-fees"),
    path("state/fees/<uuid:pk>/", StateAssessmentFeeDetailView.as_view(), name="state-fee-detail"),
    path("state/fees/<uuid:pk>/<str:action>/", StateAssessmentFeeDetailView.as_view(), name="state-fee-action"),
    path("state/fee-schedules/", StateAssessmentFeeListCreateView.as_view(), name="state-fee-schedules"),
    path("state/fee-schedules/<uuid:pk>/", StateAssessmentFeeDetailView.as_view(), name="state-fee-schedule-detail"),
    path("state/fee-schedules/<uuid:pk>/<str:action>/", StateAssessmentFeeDetailView.as_view(), name="state-fee-schedule-action"),
    path("state/certificate-validation-queue/", StateCertificateValidationListView.as_view(), name="state-certificate-validation-queue"),
    path("state/certificate-validation-queue/<uuid:pk>/", StateCertificateValidationDetailView.as_view(), name="state-certificate-validation-detail"),
    path("state/certificate-validation-queue/<uuid:pk>/approve/", StateCertificateValidationApproveView.as_view(), name="state-certificate-validation-approve"),
    path("state/certificate-validation-queue/<uuid:pk>/reject/", StateCertificateValidationRejectView.as_view(), name="state-certificate-validation-reject"),
    path("state/certificate-validation-queue/<uuid:pk>/request-clarification/", StateCertificateValidationClarificationView.as_view(), name="state-certificate-validation-clarification"),
    path("state/certificates/", StateCertificateRegistryListView.as_view(), name="state-certificates"),
    path("state/certificates/export/", StateCertificateExportView.as_view(), name="state-certificate-export"),
    path("state/certificates/<uuid:pk>/", StateCertificateRegistryDetailView.as_view(), name="state-certificate-detail"),
    path("state/certificates/<uuid:pk>/audit/", StateCertificateAuditView.as_view(), name="state-certificate-audit"),
    path("state/certificates/<uuid:pk>/suspend/", StateCertificateSuspendView.as_view(), name="state-certificate-suspend"),
    path("state/certificates/<uuid:pk>/reinstate/", StateCertificateReinstateView.as_view(), name="state-certificate-reinstate"),
    path("state/certificates/<uuid:pk>/revoke/", StateCertificateRevokeView.as_view(), name="state-certificate-revoke"),
    path("state/certificates/<uuid:pk>/replace/", StateCertificateReplaceView.as_view(), name="state-certificate-replace"),
    path("state/employers/", StateEmployerMonitoringView.as_view(), name="state-employers"),
    path("state/food-handlers/", StateFoodHandlerMonitoringView.as_view(), name="state-food-handlers"),
    path("state/illness-reports/", StateIllnessMonitoringView.as_view(), name="state-illness-reports"),
    path("state/inspections/", StateInspectionListView.as_view(), name="state-inspections"),
    path("state/inspections/<uuid:pk>/", StateInspectionDetailView.as_view(), name="state-inspection-detail"),
    path("state/inspections/<uuid:pk>/review/", StateInspectionReviewView.as_view(), name="state-inspection-review"),
    path("state/inspections/<uuid:pk>/close/", StateInspectionCloseView.as_view(), name="state-inspection-close"),
    path("state/reports/", StateReportListView.as_view(), name="state-reports"),
    path("state/reports/generate/", StateReportGenerateView.as_view(), name="state-report-generate"),
    path("state/reports/<uuid:pk>/submit/", StateReportSubmitView.as_view(), name="state-report-submit"),
    path("state/finance/dashboard/", StateFinanceDashboardView.as_view(), name="state-finance-dashboard"),
    path("state/finance/export/", StateFinanceExportView.as_view(), name="state-finance-export"),
    path("state/finance/refunds/", StateRefundListView.as_view(), name="state-finance-refunds"),
    path("state/finance/settlements/", StateSettlementListView.as_view(), name="state-finance-settlements"),
    path("state/revenue/", StateRevenueView.as_view(), name="state-revenue"),
    path("state/settlements/", StateSettlementListView.as_view(), name="state-settlements"),
    path("federal/dashboard/", FederalDashboardView.as_view(), name="federal-dashboard"),
    path("federal/finance/dashboard/", FederalFinanceDashboardView.as_view(), name="federal-finance-dashboard"),
    path("federal/finance/revenue-by-state/", FederalFinanceRevenueByStateView.as_view(), name="federal-finance-revenue-by-state"),
    path("federal/finance/subscriptions/", FederalFinanceSubscriptionsView.as_view(), name="federal-finance-subscriptions"),
    path("federal/finance/settlements/", FederalFinanceSettlementListView.as_view(), name="federal-finance-settlements"),
    path("federal/states/performance/", FederalStatePerformanceView.as_view(), name="federal-state-performance"),
    path("federal/states/<uuid:state_id>/summary/", FederalStateSummaryView.as_view(), name="federal-state-summary"),
    path("federal/certificates/", FederalCertificateRegistryView.as_view(), name="federal-certificates"),
    path("federal/certificates/analytics/", FederalCertificateAnalyticsView.as_view(), name="federal-certificate-analytics"),
    path("federal/certificates/<uuid:pk>/", FederalCertificateDetailView.as_view(), name="federal-certificate-detail"),
    path("federal/certificates/<uuid:pk>/flag/", FederalCertificateFlagView.as_view(), name="federal-certificate-flag"),
    path("federal/facilities/", FederalFacilityRegistryView.as_view(), name="federal-facilities"),
    path("federal/employers/", FederalEmployerRegistryView.as_view(), name="federal-employers"),
    path("federal/food-handlers/summary/", FederalFoodHandlerSummaryView.as_view(), name="federal-food-handler-summary"),
    path("federal/policy/", FederalPolicyView.as_view(), name="federal-policy"),
    path("federal/state-overrides/", FederalStateOverrideView.as_view(), name="federal-state-overrides"),
    path("federal/m-and-e/indicators/", FederalIndicatorsView.as_view(), name="federal-indicators"),
    path("federal/data-quality/", FederalDataQualityView.as_view(), name="federal-data-quality"),
    path("federal/audit-logs/", FederalAuditLogView.as_view(), name="federal-audit-logs"),
    path("federal/queries/", FederalQueryListCreateView.as_view(), name="federal-queries"),
    path("federal/queries/<uuid:pk>/respond/", FederalQueryRespondView.as_view(), name="federal-query-respond"),
    path("federal/queries/<uuid:pk>/close/", FederalQueryCloseView.as_view(), name="federal-query-close"),
]
