# Generated by Django 4.2.30 on 2026-05-13 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('employers', '0002_rename_employerprofile_employer_and_align_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_food_handlers', models.PositiveIntegerField(default=0)),
                ('max_locations', models.PositiveIntegerField(default=1)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
            ],
            options={
                'ordering': ['price_monthly', 'name'],
                'indexes': [models.Index(fields=['status'], name='subscriptio_status_576e10_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='employers.employer')),
                ('last_payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_subscriptions', to='payments.paymenttransaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.employersubscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employer'], name='subscriptio_employe_240717_idx'), models.Index(fields=['status'], name='subscriptio_status_f22de4_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_fad98e_idx')],
            },
        ),
    ]
