# Generated by Django 4.2.30 on 2026-05-25 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_refundrequest'),
        ('employers', '0004_employer_business_settings_and_notifications'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersubscriptionplan',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='employersubscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employersubscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployerInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=16)),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='employers.employer')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_invoice', to='payments.paymenttransaction')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.employersubscription')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['employer', 'status'], name='subscriptio_employe_739967_idx'), models.Index(fields=['due_date'], name='subscriptio_due_dat_29411c_idx')],
            },
        ),
    ]
