# Generated by Django 4.2.30 on 2026-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_employersubscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employersubscription',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employersubscription',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employersubscription',
            name='renewal_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
