# Generated by Django 4.2.30 on 2026-05-12 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodHandlerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('nin', models.CharField(max_length=32)),
                ('passport_photo', models.ImageField(blank=True, upload_to='passport_photos/')),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(default='Nigerian', max_length=80)),
                ('home_address', models.TextField()),
                ('ward', models.CharField(blank=True, max_length=120)),
                ('work_location', models.TextField(blank=True)),
                ('food_handler_category', models.CharField(choices=[('kitchen_staff', 'Kitchen staff'), ('food_preparer', 'Food preparers'), ('serving_catering', 'Serving and catering staff'), ('food_packer', 'Food packers'), ('bakery_worker', 'Bakery workers'), ('food_processing_operator', 'Food processing operators'), ('bartender', 'Bartenders'), ('dishwasher', 'Dishwashers'), ('food_delivery', 'Food delivery personnel'), ('street_vendor', 'Food stall and street food vendors'), ('food_storage_handler', 'Food storage handlers'), ('concession_worker', 'Concession stand workers'), ('airline_catering', 'Airline catering vendors'), ('train_catering', 'Train catering vendors'), ('vessel_catering', 'Cruise ship/sea vessel catering vendors'), ('livestock_meat', 'Livestock farmers, butchers, meat cutters'), ('emergency_food_worker', 'Emergency situation food workers')], max_length=64)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('system_identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('current_status', models.CharField(choices=[('profile_incomplete', 'Profile Incomplete'), ('nin_pending', 'NIN Pending'), ('certification_pending', 'Certification Pending'), ('fit', 'Fit to Handle Food'), ('temporarily_not_fit', 'Temporarily Not Fit'), ('excluded', 'Excluded from Food Handling')], db_index=True, default='profile_incomplete', max_length=32)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_handlers', to='employers.employerprofile')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_handlers', to='locations.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_handlers', to='locations.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_handler_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='food_handle_state_i_b0fe31_idx'), models.Index(fields=['lga'], name='food_handle_lga_id_469f9b_idx'), models.Index(fields=['employer'], name='food_handle_employe_331b48_idx'), models.Index(fields=['current_status'], name='food_handle_current_6a3295_idx'), models.Index(fields=['created_at'], name='food_handle_created_c10ba0_idx')],
            },
        ),
    ]
