# Generated by Django 4.2.30 on 2026-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_handlers', '0002_alter_foodhandlerprofile_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodhandlerprofile',
            name='current_status',
            field=models.CharField(choices=[('profile_incomplete', 'Profile Incomplete'), ('nin_pending', 'NIN Pending'), ('certification_pending', 'Certification Pending'), ('fit', 'Fit to Handle Food'), ('temporarily_excluded', 'Temporarily Excluded from Food Handling'), ('temporarily_not_fit', 'Temporarily Not Fit'), ('excluded', 'Excluded from Food Handling')], db_index=True, default='profile_incomplete', max_length=32),
        ),
    ]
