# Generated by Django 4.2.30 on 2026-05-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationunit_and_more'),
        ('food_handlers', '0003_alter_foodhandlerprofile_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhandlerprofile',
            name='business_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_handlers', to='organizations.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='foodhandlerprofile',
            index=models.Index(fields=['business_branch'], name='food_handle_busines_57259c_idx'),
        ),
    ]
