# Generated by Django 4.2.30 on 2026-05-13 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_rename_employerprofile_employer_and_align_policy'),
        ('food_handlers', '0003_alter_foodhandlerprofile_current_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', models.JSONField(blank=True, default=dict)),
                ('suspected_condition', models.CharField(blank=True, choices=[('general_diarrhoea_vomiting', 'General diarrhoea/vomiting'), ('cholera', 'Cholera'), ('shigella', 'Shigella'), ('hepatitis_a', 'Hepatitis A'), ('infected_skin_lesion', 'Infected skin lesion'), ('amoebic_dysentery', 'Amoebic dysentery'), ('taenia_solium', 'Taenia solium'), ('lassa_fever', 'Lassa fever'), ('other', 'Other')], max_length=64)),
                ('symptom_start_date', models.DateField(blank=True, null=True)),
                ('symptom_end_date', models.DateField(blank=True, null=True)),
                ('exclusion_start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('earliest_return_date', models.DateField(blank=True, null=True)),
                ('clearance_required', models.BooleanField(default=True)),
                ('clearance_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('cleared', 'Cleared'), ('rejected', 'Rejected'), ('clearance_required', 'Clearance Required')], db_index=True, default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('return_to_work_certificate_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illness_reports', to='employers.employer')),
                ('food_handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='illness_reports', to='food_handlers.foodhandlerprofile')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_illnesses', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_illness_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['food_handler'], name='illness_ill_food_ha_15a0a5_idx'), models.Index(fields=['employer'], name='illness_ill_employe_642f7e_idx'), models.Index(fields=['reported_by'], name='illness_ill_reporte_68b182_idx'), models.Index(fields=['clearance_status'], name='illness_ill_clearan_3f424c_idx'), models.Index(fields=['suspected_condition'], name='illness_ill_suspect_40afdd_idx'), models.Index(fields=['exclusion_start_date'], name='illness_ill_exclusi_f95cf6_idx')],
            },
        ),
    ]
