# Generated by Django 4.2.30 on 2026-05-13 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_rename_employerprofile_employer_and_align_policy'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
        ('food_handlers', '0002_alter_foodhandlerprofile_employer'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended'), ('replaced', 'Replaced'), ('pending_validation', 'Pending Validation'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=32)),
                ('qr_code_url', models.URLField(blank=True)),
                ('verification_url', models.URLField()),
                ('pdf_url', models.URLField(blank=True)),
                ('digital_signature_hash', models.CharField(max_length=128)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='assessments.medicalassessment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_certificates', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='employers.employer')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='facilities.medicalfacility')),
                ('food_handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='food_handlers.foodhandlerprofile')),
                ('issued_by_state_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('issuing_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='locations.state')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number_submitted', models.CharField(db_index=True, max_length=64)),
                ('result', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended'), ('invalid', 'Invalid'), ('not_found', 'Not Found')], db_index=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['certificate_number_submitted'], name='certificate_certifi_f49dca_idx'), models.Index(fields=['result'], name='certificate_result_dafca6_idx'), models.Index(fields=['verified_at'], name='certificate_verifie_bf97c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_validation', 'Pending Validation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('correction_requested', 'Correction Requested'), ('suspended', 'Suspended')], db_index=True, default='pending_validation', max_length=32)),
                ('request_notes', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_request', to='assessments.medicalassessment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='certificate_status_5a2349_idx'), models.Index(fields=['created_at'], name='certificate_created_1792b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_cd0c46_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['food_handler'], name='certificate_food_ha_085325_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['assessment'], name='certificate_assessm_d2328c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_31e804_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['expiry_date'], name='certificate_expiry__2f5bd0_idx'),
        ),
    ]
