# Generated by Django 4.2.30 on 2026-05-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationunit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_certificate_request_facility_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='business_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='organizations.organizationunit'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='replacement_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=96, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateverificationlog',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='certificateverificationlog',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='certificateverificationlog',
            name='verification_token_submitted',
            field=models.CharField(blank=True, db_index=True, max_length=96),
        ),
        migrations.AddField(
            model_name='certificateverificationlog',
            name='verifier_type',
            field=models.CharField(choices=[('public', 'Public'), ('inspector', 'Inspector'), ('employer', 'Employer'), ('food_handler', 'Food Handler'), ('state', 'State Ministry'), ('federal', 'Federal Ministry'), ('system', 'System')], db_index=True, default='public', max_length=32),
        ),
        migrations.AddField(
            model_name='certificateverificationlog',
            name='verifier_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_verification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificateverificationlog',
            name='result',
            field=models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended'), ('replaced', 'Replaced'), ('invalid', 'Invalid'), ('not_found', 'Not Found')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['public_id'], name='certificate_public__82a823_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_token'], name='certificate_verific_369807_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverificationlog',
            index=models.Index(fields=['verification_token_submitted'], name='certificate_verific_148ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverificationlog',
            index=models.Index(fields=['verifier_type'], name='certificate_verifie_001551_idx'),
        ),
    ]
