# Generated by Django 4.2.30 on 2026-05-23 23:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_business_branch_certificate_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousCertificateReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number_submitted', models.CharField(blank=True, db_index=True, max_length=64)),
                ('verification_token_submitted', models.CharField(blank=True, db_index=True, max_length=96)),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_contact', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_reports', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['certificate_number_submitted'], name='certificate_certifi_873ffe_idx'), models.Index(fields=['verification_token_submitted'], name='certificate_verific_696db5_idx'), models.Index(fields=['created_at'], name='certificate_created_c0fb8d_idx')],
            },
        ),
    ]
