# Generated by Django 4.2.30 on 2026-05-25 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0004_suspiciouscertificatereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('scope', models.CharField(choices=[('national', 'National'), ('state', 'State')], db_index=True, default='national', max_length=24)),
                ('ministry_name', models.CharField(default='FoodCert NG', max_length=180)),
                ('subtitle', models.CharField(default='Official Food Handler Medical Fitness Certificate', max_length=180)),
                ('logo_url', models.URLField(blank=True)),
                ('accent_color', models.CharField(default='#0f5132', max_length=7)),
                ('signatory_name', models.CharField(blank=True, max_length=160)),
                ('signatory_title', models.CharField(default='Authorized Issuing Authority', max_length=160)),
                ('footer_note', models.TextField(default='This certificate confirms fitness status only. It does not disclose lab results, diagnosis, clinical notes, or full NIN.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_templates', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='locations.state')),
            ],
            options={
                'ordering': ['scope', 'state__name', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['scope', 'state', 'is_default'], name='certificate_scope_a71015_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['is_active'], name='certificate_is_acti_4f5823_idx'),
        ),
    ]
