# Generated by Django 4.2.30 on 2026-06-09 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0005_rename_facilities__facilit_55cedd_idx_facilities__facilit_22951e_idx_and_more'),
        ('employers', '0004_employer_business_settings_and_notifications'),
        ('certificates', '0005_certificatetemplate_certificate_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('certificate_type', models.CharField(choices=[('employer_accreditation', 'Employer Accreditation'), ('facility_accreditation', 'Facility Accreditation')], db_index=True, max_length=40)),
                ('public_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('verification_token', models.CharField(blank=True, db_index=True, max_length=96, null=True, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended'), ('replaced', 'Replaced'), ('pending_validation', 'Pending Validation'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=32)),
                ('qr_code_url', models.URLField(blank=True)),
                ('verification_url', models.URLField()),
                ('pdf_url', models.URLField(blank=True)),
                ('digital_signature_hash', models.CharField(max_length=128)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accreditation_certificates', to='employers.employer')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accreditation_certificates', to='facilities.medicalfacility')),
                ('facility_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accreditation_certificates', to='facilities.facilityaccreditationapplication')),
                ('issued_by_state_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_accreditation_certificates', to=settings.AUTH_USER_MODEL)),
                ('issuing_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accreditation_certificates', to='locations.state')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_accreditation_certificates', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_accreditation_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['certificate_number'], name='certificate_certifi_fc0170_idx'), models.Index(fields=['certificate_type'], name='certificate_certifi_185255_idx'), models.Index(fields=['verification_token'], name='certificate_verific_48f19c_idx'), models.Index(fields=['employer'], name='certificate_employe_212dc5_idx'), models.Index(fields=['facility'], name='certificate_facilit_055310_idx'), models.Index(fields=['issuing_state'], name='certificate_issuing_13a931_idx'), models.Index(fields=['status'], name='certificate_status_524a2d_idx'), models.Index(fields=['expiry_date'], name='certificate_expiry__000cb7_idx')],
            },
        ),
    ]
