# Generated by Django 4.2.30 on 2026-06-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_seed_legacy_roles_and_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('inspection_checklist', 'Inspection Checklist'), ('employer_data_collection', 'Employer Data Collection'), ('employer_compliance', 'Employer Compliance Self-Assessment'), ('facility_data_collection', 'Medical Facility Data Collection'), ('facility_monthly_report', 'Medical Facility Monthly Report'), ('accreditation_checklist', 'Accreditation Checklist'), ('re_accreditation_checklist', 'Re-accreditation Checklist'), ('food_handler_survey', 'Food Handler Survey'), ('food_handler_declaration', 'Food Handler Declaration'), ('incident_report', 'Incident Report'), ('training_feedback', 'Training Feedback'), ('general_data_collection', 'General Data Collection')], max_length=50)),
                ('assigned_to_type', models.CharField(help_text='user, organization, unit, role, group', max_length=50)),
                ('assigned_to_id', models.CharField(blank=True, max_length=100)),
                ('recipient_role', models.CharField(blank=True, max_length=50)),
                ('context_type', models.CharField(blank=True, help_text='inspection, employer, facility, accreditation, general', max_length=50)),
                ('context_id', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('allow_draft', models.BooleanField(default=True)),
                ('allow_offline', models.BooleanField(default=False)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewer_role', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('reviewed', 'Reviewed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(max_length=50)),
                ('recipient_id', models.CharField(max_length=100)),
                ('role_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='not_started', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='forms.formassignment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_recipients', to='organizations.organization')),
            ],
            options={
                'ordering': ['assignment', 'recipient_type', 'recipient_id'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type', models.CharField(blank=True, max_length=50)),
                ('context_id', models.CharField(blank=True, max_length=100)),
                ('response_json', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('sync_pending', 'Sync Pending'), ('sync_failed', 'Sync Failed')], db_index=True, default='not_started', max_length=20)),
                ('sync_status', models.CharField(choices=[('online', 'Online'), ('available_offline', 'Available Offline'), ('sync_pending', 'Sync Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed'), ('conflict', 'Conflict Detected')], db_index=True, default='online', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('returned_reason', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formassignment')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='forms.formrecipient')),
                ('respondent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_responses', to='organizations.organization')),
                ('respondent_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('inspection_checklist', 'Inspection Checklist'), ('employer_data_collection', 'Employer Data Collection'), ('employer_compliance', 'Employer Compliance Self-Assessment'), ('facility_data_collection', 'Medical Facility Data Collection'), ('facility_monthly_report', 'Medical Facility Monthly Report'), ('accreditation_checklist', 'Accreditation Checklist'), ('re_accreditation_checklist', 'Re-accreditation Checklist'), ('food_handler_survey', 'Food Handler Survey'), ('food_handler_declaration', 'Food Handler Declaration'), ('incident_report', 'Incident Report'), ('training_feedback', 'Training Feedback'), ('general_data_collection', 'General Data Collection')], db_index=True, max_length=50)),
                ('target_respondent_type', models.CharField(blank=True, max_length=50)),
                ('primary_module', models.CharField(choices=[('inspections', 'Inspections'), ('employers', 'Employers / Food Businesses'), ('facilities', 'Medical Facilities'), ('accreditation', 'Accreditation'), ('food_handlers', 'Food Handlers'), ('reports', 'Reports'), ('compliance', 'Compliance Monitoring'), ('training', 'Training / Feedback'), ('incidents', 'Incident Reporting'), ('general', 'General')], db_index=True, default='general', max_length=50)),
                ('module_context', models.CharField(blank=True, help_text='Compatibility field; use primary_module for new forms.', max_length=50)),
                ('default_context_type', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='en', max_length=16)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates_created', to=settings.AUTH_USER_MODEL)),
                ('owner_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('schema_json', models.JSONField(default=dict, help_text='Sections and questions definition')),
                ('logic_json', models.JSONField(blank=True, default=dict)),
                ('scoring_json', models.JSONField(blank=True, default=dict)),
                ('conditional_logic_json', models.JSONField(blank=True, default=dict)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions_published', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms.formtemplate')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='FormResponseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_key', models.CharField(max_length=120)),
                ('repeat_group_key', models.CharField(blank=True, max_length=120)),
                ('repeat_item_id', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='form_response_attachments/')),
                ('file_url', models.URLField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('online', 'Online'), ('available_offline', 'Available Offline'), ('sync_pending', 'Sync Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed'), ('conflict', 'Conflict Detected')], db_index=True, default='online', max_length=20)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forms.formresponse')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_response_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['response', 'question_key', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponseActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_response_activity', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='forms.formresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formresponse',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='forms.formtemplate'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='template_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='forms.formtemplateversion'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='forms.formtemplate'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='template_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='forms.formtemplateversion'),
        ),
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_response_id', models.CharField(db_index=True, max_length=128)),
                ('operation_type', models.CharField(max_length=50)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('media_payload_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('available_offline', 'Available Offline'), ('sync_pending', 'Sync Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed'), ('conflict', 'Conflict Detected')], db_index=True, default='sync_pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_sync_jobs', to='forms.formassignment')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_jobs', to='forms.formresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_offline_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='forms_offli_user_id_26d1c6_idx'), models.Index(fields=['assignment', 'status'], name='forms_offli_assignm_531050_idx'), models.Index(fields=['local_response_id'], name='forms_offli_local_r_b41759_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['purpose'], name='forms_formt_purpose_9db43c_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['status'], name='forms_formt_status_f2b7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['owner_organization'], name='forms_formt_owner_o_4eccf6_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['primary_module', 'status'], name='forms_formt_primary_5fe100_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponseattachment',
            index=models.Index(fields=['response', 'question_key'], name='forms_formr_respons_04f348_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponseattachment',
            index=models.Index(fields=['sync_status'], name='forms_formr_sync_st_4dc22e_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponseactivitylog',
            index=models.Index(fields=['response', 'action'], name='forms_formr_respons_08988f_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponseactivitylog',
            index=models.Index(fields=['actor', 'created_at'], name='forms_formr_actor_i_9a2bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['status'], name='forms_formr_status_a1b130_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['sync_status'], name='forms_formr_sync_st_dd69a7_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['assignment'], name='forms_formr_assignm_e56bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['respondent_user'], name='forms_formr_respond_b22e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['context_type', 'context_id'], name='forms_formr_context_ee2bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='formrecipient',
            index=models.Index(fields=['assignment', 'status'], name='forms_formr_assignm_d5e139_idx'),
        ),
        migrations.AddIndex(
            model_name='formrecipient',
            index=models.Index(fields=['recipient_type', 'recipient_id'], name='forms_formr_recipie_d30c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='formrecipient',
            index=models.Index(fields=['organization', 'status'], name='forms_formr_organiz_517e13_idx'),
        ),
        migrations.AddConstraint(
            model_name='formrecipient',
            constraint=models.UniqueConstraint(fields=('assignment', 'recipient_type', 'recipient_id'), name='forms_unique_assignment_recipient'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['status'], name='forms_forma_status_df783d_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['purpose'], name='forms_forma_purpose_e981e8_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['assigned_to_type'], name='forms_forma_assigne_d74306_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['context_type'], name='forms_forma_context_b8339f_idx'),
        ),
    ]
