# Generated by Django 4.2.30 on 2026-05-12 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_handlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NINVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nin', models.CharField(max_length=32)),
                ('provider', models.CharField(default='mock', max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('mismatch', 'Mismatch'), ('manual_review_required', 'Manual Review Required'), ('override_approved', 'Override Approved')], db_index=True, default='pending_verification', max_length=32)),
                ('verified_full_name', models.CharField(blank=True, max_length=255)),
                ('verified_date_of_birth', models.DateField(blank=True, null=True)),
                ('verified_gender', models.CharField(blank=True, max_length=16)),
                ('verified_photo_url', models.URLField(blank=True)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mismatch_fields', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('food_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nin_verifications', to='food_handlers.foodhandlerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_nin_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['food_handler'], name='nin_verific_food_ha_adbdc8_idx'), models.Index(fields=['status'], name='nin_verific_status_627516_idx'), models.Index(fields=['created_at'], name='nin_verific_created_4c9ef7_idx')],
            },
        ),
    ]
