# Generated by Django 4.2.30 on 2026-05-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(choices=[('stool_microscopy', 'Stool Microscopy'), ('stool_culture_sensitivity', 'Stool Culture and Sensitivity'), ('hepatitis_a_antigen', 'Hepatitis A Antigen'), ('typhoid', 'Typhoid'), ('cholera', 'Cholera'), ('other', 'Other')], max_length=64)),
                ('test_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('positive', 'Positive'), ('negative', 'Negative'), ('inconclusive', 'Inconclusive'), ('repeat_required', 'Repeat Required'), ('reviewed', 'Reviewed')], db_index=True, default='requested', max_length=32)),
                ('result_value', models.CharField(blank=True, max_length=255)),
                ('result_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='assessments.medicalassessment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('resulted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulted_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment'], name='lab_tests_l_assessm_8d2674_idx'), models.Index(fields=['test_type'], name='lab_tests_l_test_ty_f3283a_idx'), models.Index(fields=['status'], name='lab_tests_l_status_816d97_idx'), models.Index(fields=['requested_at'], name='lab_tests_l_request_5703eb_idx')],
            },
        ),
    ]
