# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="lab_staff_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="labtest",
            name="result_document",
            field=models.FileField(blank=True, upload_to="lab_results/"),
        ),
        migrations.AddField(
            model_name="labtest",
            name="sample_collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labtest",
            name="submitted_to_doctor_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="labtest",
            index=models.Index(fields=["sample_collected_at"], name="lab_tests_l_sample__f6fbff_idx"),
        ),
        migrations.AddIndex(
            model_name="labtest",
            index=models.Index(fields=["submitted_to_doctor_at"], name="lab_tests_l_submitt_1936d9_idx"),
        ),
    ]
