# Generated by Django 4.2.30 on 2026-05-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0002_labtest_operational_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labtest',
            new_name='lab_tests_l_sample__b24f03_idx',
            old_name='lab_tests_l_sample__f6fbff_idx',
        ),
        migrations.RenameIndex(
            model_name='labtest',
            new_name='lab_tests_l_submitt_ab2192_idx',
            old_name='lab_tests_l_submitt_1936d9_idx',
        ),
    ]
