# Generated by Django 4.2.30 on 2026-05-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0006_labtest_doctor_review_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labtest',
            new_name='lab_tests_l_parent__c410a8_idx',
            old_name='lab_tests_l_parent__1f93e0_idx',
        ),
        migrations.RenameIndex(
            model_name='labtest',
            new_name='lab_tests_l_repeat__218e2d_idx',
            old_name='lab_tests_l_repeat__c26bc5_idx',
        ),
        migrations.RenameIndex(
            model_name='labtest',
            new_name='lab_tests_l_is_flag_aa0374_idx',
            old_name='lab_tests_l_is_flag_34277e_idx',
        ),
        migrations.RenameIndex(
            model_name='labtest',
            new_name='lab_tests_l_doctor__788865_idx',
            old_name='lab_tests_l_doctor__6a4b68_idx',
        ),
    ]
