# Generated by Django 4.2.30 on 2026-05-13 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_user_phone_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('federal_admin', 'Federal Admin'), ('state_admin', 'State Ministry Admin'), ('facility_admin', 'Medical Facility Admin'), ('doctor', 'Doctor'), ('lab_staff', 'Lab Staff'), ('employer', 'Employer'), ('food_handler', 'Food Handler'), ('inspector', 'Inspector')], db_index=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
