# Generated by Django 4.2.30 on 2026-05-13 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinvite'),
        ('organizations', '0003_organizationunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.organizationunit'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['unit'], name='accounts_us_unit_id_8bdccc_idx'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='organizations.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['organization'], name='accounts_us_organiz_1fa312_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['unit'], name='accounts_us_unit_id_693fde_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['email'], name='accounts_us_email_8f89fb_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['role'], name='accounts_us_role_31057c_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['status'], name='accounts_us_status_404b59_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_706e25_idx'),
        ),
    ]
