# Generated by Django 4.2.30 on 2026-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_unit_user_unit_restricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employer_staff_role',
            field=models.CharField(blank=True, choices=[('employer_admin', 'Employer Admin'), ('compliance_officer', 'Compliance Officer'), ('branch_manager', 'Branch Manager'), ('finance_user', 'Finance User')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='employer_staff_role',
            field=models.CharField(blank=True, choices=[('employer_admin', 'Employer Admin'), ('compliance_officer', 'Compliance Officer'), ('branch_manager', 'Branch Manager'), ('finance_user', 'Finance User')], db_index=True, max_length=32),
        ),
    ]
