# Generated by Django 4.2.30 on 2026-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_employer_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='ministry_staff_role',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
