# Generated by Django 4.2.30 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userinvite_facility_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='unit_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
