# Generated by Django 4.2.30 on 2026-06-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userinvite_unit_restricted_alter_userinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('declined', 'Declined'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
