# Generated by Django 4.2.30 on 2026-05-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('payments', '0001_initial'),
        ('food_handlers', '0002_alter_foodhandlerprofile_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0002_rename_employerprofile_employer_and_align_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.medicalfacility')),
                ('food_handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='food_handlers.foodhandlerprofile')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('appointment_booked', 'Appointment Booked'), ('declaration_submitted', 'Declaration Submitted'), ('declaration_validated', 'Declaration Validated'), ('physical_exam_completed', 'Physical Exam Completed'), ('lab_tests_pending', 'Lab Tests Pending'), ('lab_results_reviewed', 'Lab Results Reviewed'), ('vaccination_reviewed', 'Vaccination Reviewed'), ('doctor_decision_pending', 'Doctor Decision Pending'), ('fit', 'Fit'), ('temporarily_not_fit', 'Temporarily Not Fit'), ('not_fit', 'Not Fit'), ('submitted_for_state_validation', 'Submitted For State Validation'), ('certificate_issued', 'Certificate Issued'), ('closed', 'Closed')], db_index=True, default='draft', max_length=48)),
                ('declaration_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=32)),
                ('physical_exam_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=32)),
                ('lab_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=32)),
                ('vaccination_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=32)),
                ('final_decision', models.CharField(choices=[('pending', 'Pending'), ('fit', 'Fit'), ('temporarily_not_fit', 'Temporarily Not Fit'), ('not_fit', 'Not Fit'), ('requires_vaccination', 'Requires Vaccination'), ('requires_lab_test', 'Requires Lab Test'), ('requires_recheck', 'Requires Recheck'), ('requires_treatment', 'Requires Treatment'), ('requires_public_health_clearance', 'Requires Public Health Clearance'), ('return_to_work_on_date', 'Return To Work On Date')], db_index=True, default='pending', max_length=64)),
                ('return_to_work_date', models.DateField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_assessments', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='employers.employer')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='facilities.medicalfacility')),
                ('food_handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='food_handlers.foodhandlerprofile')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_assessments', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diarrhoea_vomiting_last_7_days', models.BooleanField(default=False)),
                ('fever_more_than_one_week', models.BooleanField(default=False)),
                ('skin_trouble', models.BooleanField(default=False)),
                ('boils_styes_sepsis', models.BooleanField(default=False)),
                ('discharge_eye_ear_nose_mouth', models.BooleanField(default=False)),
                ('recurring_skin_or_ear_infection', models.BooleanField(default=False)),
                ('recurring_bowel_disorder', models.BooleanField(default=False)),
                ('cholera_contact_last_5_days', models.BooleanField(default=False)),
                ('diarrhoea_vomiting_contact_last_7_days', models.BooleanField(default=False)),
                ('typhoid_paratyphoid_jaundice_contact_last_21_days', models.BooleanField(default=False)),
                ('typhoid_or_paratyphoid_carrier', models.BooleanField(default=False)),
                ('previous_or_current_typhoid', models.BooleanField(default=False)),
                ('certified_true', models.BooleanField(default=False)),
                ('risk_flag', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_declaration', to='assessments.medicalassessment')),
                ('validated_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fever', models.BooleanField(default=False)),
                ('jaundice', models.BooleanField(default=False)),
                ('skin_infection', models.BooleanField(default=False)),
                ('boils_styes_sepsis', models.BooleanField(default=False)),
                ('discharge', models.BooleanField(default=False)),
                ('diarrhoea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('sore_throat_with_fever', models.BooleanField(default=False)),
                ('cough_or_flu', models.BooleanField(default=False)),
                ('known_typhoid_carrier_history', models.BooleanField(default=False)),
                ('other_notes', models.TextField(blank=True)),
                ('examined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_examination', to='assessments.medicalassessment')),
                ('examined_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-examined_at'],
                'indexes': [models.Index(fields=['examined_by'], name='assessments_examine_42990d_idx'), models.Index(fields=['examined_at'], name='assessments_examine_6d34fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['food_handler'], name='assessments_food_ha_7aa32d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['employer'], name='assessments_employe_66295c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['facility'], name='assessments_facilit_f83b84_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['doctor'], name='assessments_doctor__e5b266_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['status'], name='assessments_status_043484_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['final_decision'], name='assessments_final_d_598f63_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalassessment',
            index=models.Index(fields=['created_at'], name='assessments_created_688198_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdeclaration',
            index=models.Index(fields=['risk_flag'], name='assessments_risk_fl_32e329_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdeclaration',
            index=models.Index(fields=['submitted_at'], name='assessments_submitt_e6695e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['food_handler'], name='assessments_food_ha_4158a2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility'], name='assessments_facilit_e62213_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='assessments_status_b397f4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='assessments_appoint_f1e83a_idx'),
        ),
    ]
