# Generated by Codex on 2026-05-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0002_appointment_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdeclaration",
            name="clarification_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_declaration_clarifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="healthdeclaration",
            name="clarification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthdeclaration",
            name="clarification_reason",
            field=models.TextField(blank=True),
        ),
    ]
