# Generated by Codex on 2026-05-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0003_healthdeclaration_clarification"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalassessment",
            name="digital_signature_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="medicalassessment",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_medical_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="medicalassessment",
            index=models.Index(fields=["signed_at"], name="assessments_signed__e5dbce_idx"),
        ),
    ]
