# Generated by Django 4.2.30 on 2026-05-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_medicalassessment_signature_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='assessments_doctor__00f435_idx',
            old_name='assessment_ap_doctor__95e9b4_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalassessment',
            new_name='assessments_signed__7338f5_idx',
            old_name='assessments_signed__e5dbce_idx',
        ),
    ]
