# Generated by Django 4.2.30 on 2026-05-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_assessment_state_validation_status_choices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='healthdeclaration',
            new_name='assessments_is_lock_cc7f30_idx',
            old_name='assessments_is_lock_8989a5_idx',
        ),
        migrations.RenameIndex(
            model_name='physicalexamination',
            new_name='assessments_risk_fl_d533ff_idx',
            old_name='assessments_risk_fl_5d221c_idx',
        ),
        migrations.RenameIndex(
            model_name='physicalexamination',
            new_name='assessments_is_comp_9c751f_idx',
            old_name='assessments_is_comp_9d5af6_idx',
        ),
    ]
