# Generated by Django 4.2.30 on 2026-06-01 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationunit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('facilities', '0005_rename_facilities__facilit_55cedd_idx_facilities__facilit_22951e_idx_and_more'),
        ('assessments', '0010_rename_assessments_is_lock_8989a5_idx_assessments_is_lock_cc7f30_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('form_type', models.CharField(choices=[('health_declaration', 'Health Declaration'), ('facility_intake', 'Facility Intake'), ('doctor_clinical_review', 'Doctor Clinical Review'), ('lab_result', 'Lab Result'), ('vaccination_review', 'Vaccination Review'), ('return_to_work', 'Return To Work'), ('illness_report', 'Illness Report'), ('state_validation_checklist', 'State Validation Checklist'), ('inspection_support', 'Inspection Support')], db_index=True, max_length=64)),
                ('scope', models.CharField(choices=[('system', 'System'), ('national', 'National'), ('state', 'State'), ('facility', 'Facility')], db_index=True, max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('active', 'Active'), ('retired', 'Retired'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('is_mandatory', models.BooleanField(db_index=True, default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessment_form_templates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_form_templates', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_form_templates', to='facilities.medicalfacility')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_form_templates', to='organizations.organization')),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='assessments.assessmentformtemplate')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_form_templates', to='locations.state')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFormSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('visibility_rules', models.JSONField(blank=True, default=dict)),
                ('required_completion', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessmentformtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('label', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('yes_no', 'Yes or No'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox Confirmation'), ('dropdown', 'Dropdown'), ('phone', 'Phone Number'), ('email', 'Email'), ('file_upload', 'File Upload'), ('temperature', 'Temperature'), ('weight', 'Weight'), ('height', 'Height'), ('blood_pressure', 'Blood Pressure'), ('pulse_rate', 'Pulse Rate'), ('symptom_checklist', 'Symptom Checklist'), ('exposure_history', 'Exposure History'), ('vaccination_date', 'Vaccination Date'), ('vaccine_dose', 'Vaccine Dose'), ('lab_result_status', 'Lab Result Status'), ('clinical_note', 'Clinical Note'), ('doctor_only_note', 'Doctor-only Note'), ('lab_only_note', 'Lab-only Note')], db_index=True, max_length=48)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('conditional_logic', models.JSONField(blank=True, default=dict)),
                ('risk_flag_rules', models.JSONField(blank=True, default=dict)),
                ('privacy_classification', models.CharField(choices=[('public_safe', 'Public Safe'), ('employer_safe_summary', 'Employer Safe Summary'), ('inspector_safe_summary', 'Inspector Safe Summary'), ('medical_sensitive', 'Medical Sensitive'), ('restricted_medical', 'Restricted Medical'), ('internal_administrative', 'Internal Administrative'), ('regulatory_restricted', 'Regulatory Restricted')], db_index=True, max_length=32)),
                ('respondent_role', models.CharField(choices=[('food_handler', 'Food Handler'), ('doctor', 'Doctor'), ('lab_staff', 'Lab Staff'), ('facility_staff', 'Facility Staff'), ('state_user', 'State User'), ('inspector', 'Inspector')], db_index=True, max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmentformsection')),
            ],
            options={
                'ordering': ['section__sort_order', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentformtemplate',
            index=models.Index(fields=['scope', 'status'], name='assess_form_scope_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentformtemplate',
            index=models.Index(fields=['form_type', 'status'], name='assess_form_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentformtemplate',
            index=models.Index(fields=['state', 'status'], name='assess_form_state_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentformtemplate',
            index=models.Index(fields=['facility', 'status'], name='assess_form_facility_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentformtemplate',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='assessments_form_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentformsection',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='assessments_unique_section_key'),
        ),
        migrations.AddIndex(
            model_name='assessmentformquestion',
            index=models.Index(fields=['privacy_classification'], name='assess_question_privacy_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentformquestion',
            index=models.Index(fields=['respondent_role', 'is_active'], name='assess_question_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentformquestion',
            constraint=models.UniqueConstraint(fields=('section', 'key'), name='assessments_unique_question_key'),
        ),
    ]
