# Generated by Django 4.2.30 on 2026-06-01 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0005_rename_facilities__facilit_55cedd_idx_facilities__facilit_22951e_idx_and_more'),
        ('locations', '0001_initial'),
        ('assessments', '0011_assessmentformtemplate_assessmentformsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalassessment',
            name='assessment_type',
            field=models.CharField(choices=[('standard', 'Standard New Assessment'), ('renewal', 'Certificate Renewal'), ('return_to_work', 'Return To Work'), ('high_risk', 'High-risk Food Handler'), ('outbreak_response', 'Outbreak Response')], db_index=True, default='standard', max_length=32),
        ),
        migrations.CreateModel(
            name='AssessmentRequirementSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('system', 'System'), ('national', 'National'), ('state', 'State'), ('facility', 'Facility')], db_index=True, max_length=16)),
                ('assessment_type', models.CharField(blank=True, choices=[('standard', 'Standard New Assessment'), ('renewal', 'Certificate Renewal'), ('return_to_work', 'Return To Work'), ('high_risk', 'High-risk Food Handler'), ('outbreak_response', 'Outbreak Response')], db_index=True, max_length=32)),
                ('food_handler_category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('employer_category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('illness_condition', models.CharField(blank=True, db_index=True, max_length=64)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('required_lab_tests', models.JSONField(blank=True, default=list)),
                ('required_vaccinations', models.JSONField(blank=True, default=list)),
                ('required_approvals', models.JSONField(blank=True, default=list)),
                ('blocking_requirements', models.JSONField(blank=True, default=list)),
                ('advisory_requirements', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_requirement_sets', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_requirement_sets', to='facilities.medicalfacility')),
                ('required_forms', models.ManyToManyField(blank=True, related_name='requirement_sets', to='assessments.assessmentformtemplate')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_requirement_sets', to='locations.state')),
            ],
            options={
                'ordering': ['scope', 'name', '-version'],
                'indexes': [models.Index(fields=['scope', 'status'], name='assess_req_scope_status_idx'), models.Index(fields=['state', 'status'], name='assess_req_state_status_idx'), models.Index(fields=['facility', 'status'], name='assess_req_facility_idx'), models.Index(fields=['assessment_type', 'status'], name='assess_req_type_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentrequirementset',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='assessments_req_version_positive'),
        ),
    ]
