# Generated by Django 4.2.30 on 2026-06-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0012_medicalassessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.PositiveIntegerField()),
                ('respondent_role', models.CharField(choices=[('food_handler', 'Food Handler'), ('doctor', 'Doctor'), ('lab_staff', 'Lab Staff'), ('facility_staff', 'Facility Staff'), ('state_user', 'State User'), ('inspector', 'Inspector')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('clarification_requested', 'Clarification Requested'), ('reopened', 'Reopened'), ('resubmitted', 'Resubmitted'), ('validated', 'Validated'), ('locked', 'Locked'), ('superseded', 'Superseded'), ('archived', 'Archived')], db_index=True, default='not_started', max_length=32)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('question_snapshot', models.JSONField(default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(db_index=True, default=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='assessments.medicalassessment')),
                ('previous_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='assessments.assessmentformresponse')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_form_responses', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentformtemplate')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_assessment_form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assessment', 'template__name', '-version'],
                'indexes': [models.Index(fields=['assessment', 'status'], name='assess_resp_assessment_idx'), models.Index(fields=['template', 'template_version'], name='assess_resp_template_idx'), models.Index(fields=['respondent', 'status'], name='assess_resp_respondent_idx'), models.Index(fields=['is_locked'], name='assess_resp_locked_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentformresponse',
            constraint=models.CheckConstraint(check=models.Q(('template_version__gte', 1)), name='assessments_response_template_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentformresponse',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='assessments_response_version_positive'),
        ),
    ]
