# Generated by Django 4.2.30 on 2026-06-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0013_assessmentformresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentformtemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('active', 'Active'), ('retired', 'Retired'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentformtemplate',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentformtemplate',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentformtemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentformtemplate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessment_form_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
