# Generated by Django 4.2.30 on 2026-06-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0014_assessmentformtemplate_review_fields_and_changes_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentformtemplate",
            name="base_template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="descendant_templates", to="assessments.assessmentformtemplate"),
        ),
        migrations.AddField(
            model_name="assessmentformtemplate",
            name="owner_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentformtemplate",
            name="owner_level",
            field=models.CharField(choices=[("federal", "Federal"), ("state", "State"), ("facility", "Facility")], db_index=True, default="federal", max_length=16),
        ),
        migrations.AddField(
            model_name="assessmentformtemplate",
            name="superseded_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="superseded_templates", to="assessments.assessmentformtemplate"),
        ),
        migrations.AddField(
            model_name="assessmentformsection",
            name="deletable_by_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentformsection",
            name="editable_by_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentformsection",
            name="inherited_from_section",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="derived_sections", to="assessments.assessmentformsection"),
        ),
        migrations.AddField(
            model_name="assessmentformsection",
            name="locked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="assessmentformsection",
            name="owner_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentformsection",
            name="owner_level",
            field=models.CharField(choices=[("federal", "Federal"), ("state", "State"), ("facility", "Facility")], db_index=True, default="federal", max_length=16),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="deletable_by_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="editable_by_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="inherited_from_question",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="derived_questions", to="assessments.assessmentformquestion"),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="locked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="owner_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="owner_level",
            field=models.CharField(choices=[("federal", "Federal"), ("state", "State"), ("facility", "Facility")], db_index=True, default="federal", max_length=16),
        ),
        migrations.AddField(
            model_name="assessmentformquestion",
            name="risk_flag",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="AssessmentFormTemplateSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merged_schema", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("assessment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="declaration_template_snapshot", to="assessments.medicalassessment")),
                ("facility_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="facility_snapshots", to="assessments.assessmentformtemplate")),
                ("federal_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="federal_snapshots", to="assessments.assessmentformtemplate")),
                ("state_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="state_snapshots", to="assessments.assessmentformtemplate")),
            ],
            options={"ordering": ["-generated_at"]},
        ),
        migrations.AddField(
            model_name="assessmentformresponse",
            name="template_snapshot",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="responses", to="assessments.assessmentformtemplatesnapshot"),
        ),
        migrations.CreateModel(
            name="AssessmentFormTemplateAdoption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adopted_by_level", models.CharField(choices=[("federal", "Federal"), ("state", "State"), ("facility", "Facility")], db_index=True, max_length=16)),
                ("adopted_by_id", models.UUIDField(db_index=True)),
                ("adopted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(db_index=True, default="active", max_length=16)),
                ("child_template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parent_adoptions", to="assessments.assessmentformtemplate")),
                ("parent_template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="child_adoptions", to="assessments.assessmentformtemplate")),
            ],
            options={"ordering": ["-adopted_at"]},
        ),
        migrations.AddIndex(
            model_name="assessmentformtemplateadoption",
            index=models.Index(fields=["adopted_by_level", "adopted_by_id"], name="assess_form_adopt_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentformtemplateadoption",
            index=models.Index(fields=["status"], name="assess_form_adopt_status_idx"),
        ),
    ]
