# Generated by Django 4.2.30 on 2026-06-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_assessment_lab_assignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalassessment',
            new_name='assessments_assigne_64ab79_idx',
            old_name='assessments_assigne_e49135_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalassessment',
            new_name='assessments_assigne_b60106_idx',
            old_name='assessments_assigne_b242da_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalassessment',
            new_name='assessments_identit_566861_idx',
            old_name='assessments_identit_a8f4c8_idx',
        ),
    ]
