# Generated by Django 4.2.30 on 2026-05-13 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('locations', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.UUIDField(blank=True, db_index=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facility_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('settlement_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='facilities.medicalfacility')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.paymenttransaction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='locations.state')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility'], name='settlements_facilit_7c5c6c_idx'), models.Index(fields=['state'], name='settlements_state_i_9c33ab_idx'), models.Index(fields=['payment_transaction'], name='settlements_payment_09aec5_idx'), models.Index(fields=['settlement_status'], name='settlements_settlem_2cda24_idx')],
            },
        ),
    ]
