# Generated by Django 4.2.30 on 2026-05-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='assessments.medicalassessment'),
        ),
    ]
