# Generated by Django 4.2.30 on 2026-05-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_settlement_dispute_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_dispute_800255_idx',
            old_name='settlements_dispute_4d31cc_idx',
        ),
    ]
