# Generated by Django 4.2.30 on 2026-05-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_receipt_line_items'),
        ('settlements', '0004_rename_settlements_dispute_4d31cc_idx_settlements_dispute_800255_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='eligibility_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='eligibility_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='fee_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.assessmentfee'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='payments.paymentallocation'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payment_allocation'], name='settlements_payment_90876b_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['fee_schedule'], name='settlements_fee_sch_db8474_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_allocation__isnull', True)), fields=('payment_transaction', 'assessment'), name='unique_legacy_payment_assessment_settlement'),
        ),
    ]
