# Generated by Django 4.2.30 on 2026-05-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlements', '0005_settlement_eligibility_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('settlement_count', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('facility_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('state_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=160)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='settlement',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='last_payout_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payout_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settlement',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('held', 'Held'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='settlementbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlement_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlement_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementbatch',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_settlement_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='settlements.settlementbatch'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['batch'], name='settlements_batch_i_bf0705_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['status'], name='settlements_status_3d300d_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['created_at'], name='settlements_created_8752c1_idx'),
        ),
    ]
