# Generated by Django 4.2.30 on 2026-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='file_format',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=16),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('employer_compliance', 'Employer Compliance'), ('employer_certificates', 'Employer Certificate Expiry'), ('employer_vaccinations', 'Employer Vaccination Compliance'), ('facility_performance', 'Facility Performance'), ('state_monthly', 'State Monthly'), ('national', 'National'), ('vaccination_coverage', 'Vaccination Coverage'), ('illness_trends', 'Illness Trends'), ('inspection_outcomes', 'Inspection Outcomes')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('employer_compliance', 'Employer Compliance'), ('employer_certificates', 'Employer Certificate Expiry'), ('employer_vaccinations', 'Employer Vaccination Compliance'), ('facility_performance', 'Facility Performance'), ('state_monthly', 'State Monthly'), ('national', 'National'), ('vaccination_coverage', 'Vaccination Coverage'), ('illness_trends', 'Illness Trends'), ('inspection_outcomes', 'Inspection Outcomes')], db_index=True, max_length=64),
        ),
    ]
