# Generated by Django 4.2.30 on 2026-05-27 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_alter_organizationunit_unit_type'),
        ('reports', '0004_assessment_detail_report_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='data_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='reporting_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='reporting_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='review_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='locations.state'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='submitted_to_federal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed'), ('submitted', 'Submitted'), ('returned_for_correction', 'Returned for Correction'), ('accepted', 'Accepted'), ('archived', 'Archived')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['organization'], name='reports_gen_organiz_6fe9de_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['state'], name='reports_gen_state_i_896cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['reporting_period_start', 'reporting_period_end'], name='reports_gen_reporti_29a1e4_idx'),
        ),
    ]
