# Generated by Django 4.2.30 on 2026-05-27 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_generatedreport_data_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=100)),
                ('scope', models.CharField(db_index=True, max_length=50)),
                ('output_formats', models.JSONField(blank=True, default=list)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('required_permissions', models.JSONField(blank=True, default=list)),
                ('privacy_level', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'name'],
                'indexes': [models.Index(fields=['code'], name='reports_rep_code_bb9e11_idx'), models.Index(fields=['scope', 'is_active'], name='reports_rep_scope_9760fe_idx'), models.Index(fields=['privacy_level'], name='reports_rep_privacy_0336e9_idx')],
            },
        ),
    ]
