# Generated by Django 4.2.30 on 2026-05-27 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationunit_unit_type'),
        ('locations', '0001_initial'),
        ('reports', '0006_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('numerator_definition', models.TextField(blank=True)),
                ('denominator_definition', models.TextField(blank=True)),
                ('formula', models.TextField()),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('reporting_frequency', models.CharField(db_index=True, max_length=50)),
                ('disaggregation_fields', models.JSONField(blank=True, default=list)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('visualization_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MEIndicatorValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('calculated_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('disaggregation', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.meindicator')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='me_indicator_values', to='locations.lga')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='me_indicator_values', to='organizations.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='me_indicator_values', to='locations.state')),
            ],
            options={
                'ordering': ['-period_end', 'indicator__category', 'indicator__name'],
            },
        ),
        migrations.AddIndex(
            model_name='meindicator',
            index=models.Index(fields=['code'], name='reports_mei_code_d06ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicator',
            index=models.Index(fields=['category', 'is_active'], name='reports_mei_categor_04be89_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicator',
            index=models.Index(fields=['reporting_frequency'], name='reports_mei_reporti_217384_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicatorvalue',
            index=models.Index(fields=['indicator', 'period_start', 'period_end'], name='reports_mei_indicat_375ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicatorvalue',
            index=models.Index(fields=['state', 'period_end'], name='reports_mei_state_i_c92788_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicatorvalue',
            index=models.Index(fields=['lga', 'period_end'], name='reports_mei_lga_id_babc09_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicatorvalue',
            index=models.Index(fields=['organization', 'period_end'], name='reports_mei_organiz_1c0219_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicatorvalue',
            index=models.Index(fields=['calculated_at'], name='reports_mei_calcula_a51567_idx'),
        ),
    ]
