# Generated by Django 4.2.30 on 2026-05-27 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_meindicator_meindicatorvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dashboard_scope', models.CharField(db_index=True, max_length=50)),
                ('widget_type', models.CharField(db_index=True, max_length=50)),
                ('metric_code', models.CharField(blank=True, max_length=100)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('required_permissions', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['dashboard_scope', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='reports_das_code_04191c_idx'), models.Index(fields=['dashboard_scope', 'is_active'], name='reports_das_dashboa_efb306_idx'), models.Index(fields=['widget_type'], name='reports_das_widget__103de8_idx')],
            },
        ),
    ]
