# Generated by Django 4.2.30 on 2026-05-27 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationunit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_dashboardwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=50)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(db_index=True, max_length=100)),
                ('target_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], db_index=True, default='open', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_data_quality_issues', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_quality_issues', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_data_quality_issues', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_quality_issues', to='locations.state')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_type'], name='reports_dat_issue_t_bccca4_idx'), models.Index(fields=['severity', 'status'], name='reports_dat_severit_51869e_idx'), models.Index(fields=['module', 'target_type'], name='reports_dat_module_74e383_idx'), models.Index(fields=['state', 'status'], name='reports_dat_state_i_532543_idx'), models.Index(fields=['organization', 'status'], name='reports_dat_organiz_cfdb97_idx'), models.Index(fields=['assigned_to', 'status'], name='reports_dat_assigne_18968f_idx'), models.Index(fields=['resolved_at'], name='reports_dat_resolve_d7face_idx')],
            },
        ),
    ]
