# Generated by Django 4.2.30 on 2026-05-27 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0009_dataqualityissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], db_index=True, max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], max_length=20)),
                ('delivery_channels', models.JSONField(blank=True, default=list)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_reports', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['next_run_at', 'name'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='reports_sch_owner_i_19f9ac_idx'), models.Index(fields=['report_template', 'is_active'], name='reports_sch_report__27e512_idx'), models.Index(fields=['schedule_frequency'], name='reports_sch_schedul_713b39_idx'), models.Index(fields=['next_run_at'], name='reports_sch_next_ru_32a38e_idx')],
            },
        ),
    ]
