from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0010_scheduledreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDataset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("module_source", models.CharField(db_index=True, max_length=100)),
                ("allowed_account_types", models.JSONField(blank=True, default=list)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("available_fields", models.JSONField(blank=True, default=list)),
                ("field_labels", models.JSONField(blank=True, default=dict)),
                ("field_types", models.JSONField(blank=True, default=dict)),
                ("sensitive_fields", models.JSONField(blank=True, default=list)),
                ("default_filters", models.JSONField(blank=True, default=dict)),
                ("joinable_datasets", models.JSONField(blank=True, default=list)),
                ("aggregation_rules", models.JSONField(blank=True, default=dict)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("privacy_level", models.CharField(choices=[("public", "Public"), ("internal", "Internal"), ("confidential", "Confidential"), ("pii", "PII"), ("medical", "Medical"), ("financial", "Financial"), ("security", "Security")], db_index=True, default="internal", max_length=32)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["module_source", "name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardCanvas",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_type", models.CharField(choices=[("federal", "Federal Ministry"), ("state", "State Ministry"), ("employer", "Employer / Food Business"), ("medical_facility", "Medical Facility"), ("platform_admin", "Platform Admin")], db_index=True, max_length=32)),
                ("scope_type", models.CharField(choices=[("private", "Private"), ("organization", "Organization"), ("role_based", "Role Based"), ("selected_users", "Selected Users"), ("federal_only", "Federal Only"), ("state_only", "State Only"), ("public", "Public")], db_index=True, default="private", max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("layout_config", models.JSONField(blank=True, default=dict)),
                ("global_filters", models.JSONField(blank=True, default=list)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("privacy_metadata", models.JSONField(blank=True, default=dict)),
                ("is_draft", models.BooleanField(db_index=True, default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboard_canvases", to="organizations.organization")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dashboard_canvases", to=settings.AUTH_USER_MODEL)),
                ("state", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboard_canvases", to="locations.state")),
            ],
            options={
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="PublishedDashboard",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_label", models.CharField(blank=True, default="", max_length=64)),
                ("visibility_scope", models.CharField(choices=[("private", "Private"), ("organization", "Organization"), ("role_based", "Role Based"), ("selected_users", "Selected Users"), ("federal_only", "Federal Only"), ("state_only", "State Only"), ("public", "Public")], db_index=True, default="private", max_length=32)),
                ("share_settings", models.JSONField(blank=True, default=dict)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="published_versions", to="reports.dashboardcanvas")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_dashboards", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("account_type", models.CharField(choices=[("federal", "Federal Ministry"), ("state", "State Ministry"), ("employer", "Employer / Food Business"), ("medical_facility", "Medical Facility"), ("platform_admin", "Platform Admin")], db_index=True, max_length=32)),
                ("scope_type", models.CharField(choices=[("private", "Private"), ("organization", "Organization"), ("role_based", "Role Based"), ("selected_users", "Selected Users"), ("federal_only", "Federal Only"), ("state_only", "State Only"), ("public", "Public")], db_index=True, default="private", max_length=32)),
                ("template_config", models.JSONField(blank=True, default=dict)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("privacy_metadata", models.JSONField(blank=True, default=dict)),
                ("is_system_template", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboard_templates", to=settings.AUTH_USER_MODEL)),
                ("source_canvas", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="templates", to="reports.dashboardcanvas")),
                ("source_published_dashboard", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="templates", to="reports.publisheddashboard")),
            ],
            options={
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsWorksheet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_type", models.CharField(choices=[("federal", "Federal Ministry"), ("state", "State Ministry"), ("employer", "Employer / Food Business"), ("medical_facility", "Medical Facility"), ("platform_admin", "Platform Admin")], db_index=True, max_length=32)),
                ("scope_type", models.CharField(choices=[("private", "Private"), ("organization", "Organization"), ("role_based", "Role Based"), ("selected_users", "Selected Users"), ("federal_only", "Federal Only"), ("state_only", "State Only"), ("public", "Public")], db_index=True, default="private", max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("metrics", models.JSONField(blank=True, default=list)),
                ("dimensions", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=list)),
                ("aggregations", models.JSONField(blank=True, default=list)),
                ("derived_fields", models.JSONField(blank=True, default=list)),
                ("query_rules", models.JSONField(blank=True, default=dict)),
                ("chart_recommendation", models.CharField(blank=True, default="", max_length=50)),
                ("preview_output", models.JSONField(blank=True, default=dict)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("privacy_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_template", models.BooleanField(db_index=True, default=False)),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="worksheets", to="reports.analyticsdataset")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytics_worksheets", to="organizations.organization")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_worksheets", to=settings.AUTH_USER_MODEL)),
                ("state", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytics_worksheets", to="locations.state")),
            ],
            options={
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsWidget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_type", models.CharField(choices=[("federal", "Federal Ministry"), ("state", "State Ministry"), ("employer", "Employer / Food Business"), ("medical_facility", "Medical Facility"), ("platform_admin", "Platform Admin")], db_index=True, max_length=32)),
                ("scope_type", models.CharField(choices=[("private", "Private"), ("organization", "Organization"), ("role_based", "Role Based"), ("selected_users", "Selected Users"), ("federal_only", "Federal Only"), ("state_only", "State Only"), ("public", "Public")], db_index=True, default="private", max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("widget_type", models.CharField(db_index=True, max_length=50)),
                ("visual_config", models.JSONField(blank=True, default=dict)),
                ("filter_behavior", models.JSONField(blank=True, default=dict)),
                ("refresh_behavior", models.JSONField(blank=True, default=dict)),
                ("export_options", models.JSONField(blank=True, default=dict)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("privacy_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytics_widgets", to="organizations.organization")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_widgets", to=settings.AUTH_USER_MODEL)),
                ("state", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytics_widgets", to="locations.state")),
                ("worksheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="widgets", to="reports.analyticsworksheet")),
            ],
            options={
                "ordering": ["account_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="DashboardCanvasBlock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("block_type", models.CharField(choices=[("widget", "Widget Block"), ("text", "Text Block"), ("filter", "Filter Block"), ("ai_insight", "AI Insight Block"), ("dataset_preview", "Dataset Preview Block"), ("quick_action", "Quick Action Block"), ("divider", "Divider / Section Header")], db_index=True, max_length=32)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("position", models.JSONField(blank=True, default=dict)),
                ("visibility_rules", models.JSONField(blank=True, default=dict)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("privacy_metadata", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocks", to="reports.dashboardcanvas")),
                ("widget", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="canvas_blocks", to="reports.analyticswidget")),
            ],
            options={
                "ordering": ["canvas", "sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(model_name="analyticsdataset", index=models.Index(fields=["code"], name="reports_anal_code_1fdf2c_idx")),
        migrations.AddIndex(model_name="analyticsdataset", index=models.Index(fields=["module_source", "is_active"], name="reports_anal_module__8d68a0_idx")),
        migrations.AddIndex(model_name="analyticsdataset", index=models.Index(fields=["privacy_level", "is_active"], name="reports_anal_privacy_d6f5c9_idx")),
        migrations.AddIndex(model_name="dashboardcanvas", index=models.Index(fields=["owner", "is_active"], name="reports_das_owner_02df0e_idx")),
        migrations.AddIndex(model_name="dashboardcanvas", index=models.Index(fields=["organization", "is_active"], name="reports_das_organiz_f0deca_idx")),
        migrations.AddIndex(model_name="dashboardcanvas", index=models.Index(fields=["state", "is_active"], name="reports_das_state_i_4f1a7f_idx")),
        migrations.AddIndex(model_name="dashboardcanvas", index=models.Index(fields=["account_type", "scope_type"], name="reports_das_account_57b239_idx")),
        migrations.AddIndex(model_name="dashboardcanvas", index=models.Index(fields=["is_draft", "is_active"], name="reports_das_is_dra_0b8a5b_idx")),
        migrations.AddIndex(model_name="publisheddashboard", index=models.Index(fields=["canvas", "is_active"], name="reports_pub_canvas__6e39c6_idx")),
        migrations.AddIndex(model_name="publisheddashboard", index=models.Index(fields=["visibility_scope", "is_active"], name="reports_pub_visibil_582d16_idx")),
        migrations.AddIndex(model_name="publisheddashboard", index=models.Index(fields=["published_by", "is_active"], name="reports_pub_publish_aab8d1_idx")),
        migrations.AddIndex(model_name="dashboardtemplate", index=models.Index(fields=["account_type", "is_active"], name="reports_das_account_63f232_idx")),
        migrations.AddIndex(model_name="dashboardtemplate", index=models.Index(fields=["scope_type", "is_active"], name="reports_das_scope_t_4f20f4_idx")),
        migrations.AddIndex(model_name="dashboardtemplate", index=models.Index(fields=["is_system_template", "is_active"], name="reports_das_is_sys_d52d5f_idx")),
        migrations.AddIndex(model_name="analyticsworksheet", index=models.Index(fields=["owner", "is_active"], name="reports_ana_owner_9d04b6_idx")),
        migrations.AddIndex(model_name="analyticsworksheet", index=models.Index(fields=["organization", "is_active"], name="reports_ana_organiz_38b44c_idx")),
        migrations.AddIndex(model_name="analyticsworksheet", index=models.Index(fields=["state", "is_active"], name="reports_ana_state_i_18f7a9_idx")),
        migrations.AddIndex(model_name="analyticsworksheet", index=models.Index(fields=["account_type", "scope_type"], name="reports_ana_account_b9c4d3_idx")),
        migrations.AddIndex(model_name="analyticsworksheet", index=models.Index(fields=["dataset", "is_active"], name="reports_ana_dataset_37f3a2_idx")),
        migrations.AddIndex(model_name="analyticswidget", index=models.Index(fields=["owner", "is_active"], name="reports_ana_owner_3a0ae1_idx")),
        migrations.AddIndex(model_name="analyticswidget", index=models.Index(fields=["organization", "is_active"], name="reports_ana_organiz_86c3be_idx")),
        migrations.AddIndex(model_name="analyticswidget", index=models.Index(fields=["state", "is_active"], name="reports_ana_state_i_c6b92e_idx")),
        migrations.AddIndex(model_name="analyticswidget", index=models.Index(fields=["account_type", "scope_type"], name="reports_ana_account_a77415_idx")),
        migrations.AddIndex(model_name="analyticswidget", index=models.Index(fields=["worksheet", "is_active"], name="reports_ana_workshe_71aeb3_idx")),
        migrations.AddIndex(model_name="dashboardcanvasblock", index=models.Index(fields=["canvas", "sort_order"], name="reports_das_canvas__8b1ef4_idx")),
        migrations.AddIndex(model_name="dashboardcanvasblock", index=models.Index(fields=["block_type", "is_active"], name="reports_das_block_t_03ba2d_idx")),
        migrations.AddIndex(model_name="dashboardcanvasblock", index=models.Index(fields=["widget", "is_active"], name="reports_das_widget__9d43be_idx")),
    ]
