# Generated by Django 4.2.30 on 2026-07-02 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0015_rename_reports_anal_code_1fdf2c_idx_reports_ana_code_173e5f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcanvasblock',
            name='block_type',
            field=models.CharField(choices=[('widget', 'Widget Block'), ('text', 'Text Block'), ('filter', 'Filter Block'), ('ai_insight', 'AI Insight Block'), ('dataset_preview', 'Dataset Preview Block'), ('quick_action', 'Quick Action Block'), ('divider', 'Divider / Section Header'), ('kpi_card', 'KPI Card Block')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='KpiCardDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='lucide-react icon name, e.g. ClipboardCheck', max_length=64)),
                ('source_type', models.CharField(choices=[('dataset', 'Dataset Aggregation'), ('snapshot', 'Service Snapshot Key')], db_index=True, default='dataset', max_length=16)),
                ('dataset_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metric', models.CharField(blank=True, help_text='Dataset field the aggregation reads (blank = row count)', max_length=150)),
                ('aggregation', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('latest', 'Latest')], default='count', max_length=16)),
                ('filters', models.JSONField(blank=True, default=list, help_text='[{field, operator, value}] applied before aggregation')),
                ('snapshot_key', models.CharField(blank=True, help_text='Cards payload key when source_type=snapshot', max_length=150)),
                ('format', models.CharField(choices=[('number', 'Number'), ('percent', 'Percent'), ('currency', 'Currency')], default='number', max_length=16)),
                ('trend', models.JSONField(blank=True, default=dict, help_text='{"compare_to": "prev_period", "window": "30d", "date_field": "created_at"}')),
                ('target', models.JSONField(blank=True, default=dict, help_text='{"operator": "lte", "warning": 1, "critical": 10} thresholds for status coloring')),
                ('detail', models.CharField(blank=True, help_text='Supporting caption shown under the value', max_length=255)),
                ('allowed_account_types', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='reports_kpi_categor_23ed29_idx'), models.Index(fields=['source_type'], name='reports_kpi_source__5a0453_idx')],
            },
        ),
    ]
