# Generated by Django 4.2.30 on 2026-05-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_handlers', '0002_alter_foodhandlerprofile_employer'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_type', models.CharField(choices=[('typhoid', 'Typhoid'), ('hepatitis_a', 'Hepatitis A'), ('other', 'Other')], max_length=32)),
                ('vaccine_name', models.CharField(blank=True, max_length=160)),
                ('dose_number', models.PositiveSmallIntegerField(default=1)),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('missing', 'Missing'), ('doctor_cleared', 'Doctor Cleared'), ('second_dose_due', 'Second Dose Due')], db_index=True, default='missing', max_length=32)),
                ('doctor_clearance', models.BooleanField(default=False)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='assessments.medicalassessment')),
                ('food_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='food_handlers.foodhandlerprofile')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_administered', '-created_at'],
                'indexes': [models.Index(fields=['food_handler'], name='vaccination_food_ha_b20e41_idx'), models.Index(fields=['assessment'], name='vaccination_assessm_b4f523_idx'), models.Index(fields=['vaccine_type'], name='vaccination_vaccine_21a75d_idx'), models.Index(fields=['status'], name='vaccination_status_f75cbe_idx'), models.Index(fields=['expiry_date'], name='vaccination_expiry__3f75b4_idx')],
            },
        ),
    ]
