# Generated by Django 4.2.30 on 2026-05-12 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('is_fct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='locations_s_code_f8d7d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgas', to='locations.state')),
            ],
            options={
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='locations.lga')),
            ],
            options={
                'ordering': ['lga__name', 'name'],
                'indexes': [models.Index(fields=['lga'], name='locations_w_lga_id_2fa513_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('lga', 'name'), name='unique_ward_per_lga'),
        ),
        migrations.AddIndex(
            model_name='lga',
            index=models.Index(fields=['state'], name='locations_l_state_i_65a8c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='lga',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_lga_per_state'),
        ),
    ]
