# Generated by Django 4.2.30 on 2026-05-13 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_type', models.CharField(choices=[('food_handler', 'Food Handler'), ('employer', 'Employer'), ('facility', 'Facility'), ('platform', 'Platform')], max_length=32)),
                ('related_entity_type', models.CharField(max_length=120)),
                ('related_entity_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_provider', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('internal_reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer_user'], name='payments_pa_payer_u_be5199_idx'), models.Index(fields=['payer_type'], name='payments_pa_payer_t_2d1faa_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='payments_pa_related_21d43f_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'), models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_type', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('state_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('facility_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_fees', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_fees', to='locations.state')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['state'], name='payments_as_state_i_050345_idx'), models.Index(fields=['facility_type'], name='payments_as_facilit_d4bad9_idx'), models.Index(fields=['status'], name='payments_as_status_33c8eb_idx'), models.Index(fields=['effective_from', 'effective_to'], name='payments_as_effecti_565a52_idx')],
            },
        ),
    ]
