# Generated by Django 4.2.30 on 2026-05-25 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=20)),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('encrypted_secret_key', models.TextField(blank=True)),
                ('webhook_secret', models.TextField(blank=True)),
                ('callback_url', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('supported_methods', models.JSONField(blank=True, default=list)),
                ('supports_refunds', models.BooleanField(default=False)),
                ('supports_transfers', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='received', max_length=24)),
                ('processing_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_code'], name='payments_pa_provide_978196_idx'), models.Index(fields=['event_type'], name='payments_pa_event_t_14989d_idx'), models.Index(fields=['provider_reference'], name='payments_pa_provide_2a492e_idx'), models.Index(fields=['processing_status'], name='payments_pa_process_aeb65a_idx'), models.Index(fields=['created_at'], name='payments_pa_created_81db6f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentprovider',
            index=models.Index(fields=['code'], name='payments_pa_code_9ba7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentprovider',
            index=models.Index(fields=['environment'], name='payments_pa_environ_c01d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentprovider',
            index=models.Index(fields=['is_active'], name='payments_pa_is_acti_a287c6_idx'),
        ),
    ]
