# Generated by Django 4.2.30 on 2026-05-25 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_paymentprovider_paymentwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentfee',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentfee',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessment_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentfee',
            name='fee_name',
            field=models.CharField(default='Assessment fee', max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentfee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentfee',
            name='provider_fee_handling',
            field=models.CharField(default='deduct_from_platform', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentfee',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('replaced', 'Replaced'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=24),
        ),
    ]
