# Generated by Django 4.2.30 on 2026-05-25 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('facilities', '0005_rename_facilities__facilit_55cedd_idx_facilities__facilit_22951e_idx_and_more'),
        ('payments', '0003_assessmentfee_approved_at_assessmentfee_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_type', models.CharField(choices=[('food_handler', 'Food Handler'), ('employer', 'Employer'), ('facility', 'Facility'), ('platform', 'Platform')], max_length=32)),
                ('payment_purpose', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('receipt_url', models.URLField(blank=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='facilities.medicalfacility')),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.paymenttransaction')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='locations.state')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='payments_re_receipt_8aa2fc_idx'), models.Index(fields=['payer_type'], name='payments_re_payer_t_ec7408_idx'), models.Index(fields=['payment_purpose'], name='payments_re_payment_f5fd79_idx'), models.Index(fields=['issued_at'], name='payments_re_issued__879a13_idx')],
            },
        ),
    ]
