# Generated by Django 4.2.30 on 2026-05-25 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_rename_facilities__facilit_55cedd_idx_facilities__facilit_22951e_idx_and_more'),
        ('locations', '0001_initial'),
        ('assessments', '0010_rename_assessments_is_lock_8989a5_idx_assessments_is_lock_cc7f30_idx_and_more'),
        ('payments', '0004_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facility_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('held', 'Held'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed')], db_index=True, default='allocated', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='assessments.medicalassessment')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='facilities.medicalfacility')),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='payments.assessmentfee')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.paymenttransaction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='locations.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('collection', 'Collection'), ('facility_payable', 'Facility Payable'), ('state_revenue', 'State Revenue'), ('platform_revenue', 'Platform Revenue'), ('provider_fee', 'Provider Fee'), ('refund', 'Refund'), ('reversal', 'Reversal')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('account', models.CharField(db_index=True, max_length=80)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.paymentallocation')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['payment_transaction'], name='payments_pa_payment_0818a5_idx'), models.Index(fields=['allocation'], name='payments_pa_allocat_e0cad5_idx'), models.Index(fields=['entry_type'], name='payments_pa_entry_t_4bee96_idx'), models.Index(fields=['account'], name='payments_pa_account_469456_idx'), models.Index(fields=['created_at'], name='payments_pa_created_7b41d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment_transaction'], name='payments_pa_payment_a48110_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['assessment'], name='payments_pa_assessm_c136bb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['fee_schedule'], name='payments_pa_fee_sch_f31657_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['facility'], name='payments_pa_facilit_788848_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['state'], name='payments_pa_state_i_fb22ba_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['status'], name='payments_pa_status_a87b63_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment_transaction', 'assessment'), name='unique_payment_assessment_allocation'),
        ),
    ]
