# Generated by Django 4.2.30 on 2026-05-25 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_paymentallocation_paymentledgerentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=32)),
                ('provider_refund_reference', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.paymenttransaction')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_transaction'], name='payments_re_payment_63dc12_idx'), models.Index(fields=['requested_by'], name='payments_re_request_6795e1_idx'), models.Index(fields=['status'], name='payments_re_status_ab5bbd_idx'), models.Index(fields=['created_at'], name='payments_re_created_f09531_idx')],
            },
        ),
    ]
