# Generated by Django 4.2.30 on 2026-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
