# Generated by Django 4.2.30 on 2026-05-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_receipt_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='payment_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.paymentallocation'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
