# Generated by Django 4.2.30 on 2026-05-26 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_refundrequest_payment_allocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(db_index=True, max_length=64)),
                ('provider_reference', models.CharField(db_index=True, max_length=255)),
                ('internal_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('missing_internal', 'Missing Internal'), ('missing_provider', 'Missing Provider'), ('amount_mismatch', 'Amount Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('duplicate_provider_reference', 'Duplicate Provider Reference'), ('manually_resolved', 'Manually Resolved')], db_index=True, max_length=40)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to='payments.paymenttransaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payment_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_code', 'status'], name='payments_pa_provide_f59279_idx'), models.Index(fields=['provider_code', 'provider_reference'], name='payments_pa_provide_f15f1d_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_bf64c2_idx'), models.Index(fields=['created_at'], name='payments_pa_created_5bdffd_idx')],
            },
        ),
    ]
