# Generated by Django 4.2.30 on 2026-06-13 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0009_paymentreconciliationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_code', models.CharField(db_index=True, default='food_handler_assessment', max_length=80)),
                ('fee_name', models.CharField(default='FoodCert platform fee', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('replaced', 'Replaced'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_fee_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['fee_code', 'status'], name='payments_pl_fee_cod_2f013b_idx'), models.Index(fields=['effective_from', 'effective_to'], name='payments_pl_effecti_740b82_idx')],
            },
        ),
    ]
