# Generated by Codex on 2026-06-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MEIndicatorValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("progress_value_numeric", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("cumulative_value_numeric", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("qualitative_value_text", models.TextField(blank=True, default="")),
                ("qualitative_rating", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("value_source", models.CharField(choices=[("manual", "Manual"), ("form", "Form"), ("indicator", "Indicator"), ("document", "Document"), ("import", "Import")], default="manual", max_length=16)),
                ("source_reference_id", models.CharField(blank=True, default="", max_length=128)),
                ("approval_status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("approved", "Approved"), ("rejected", "Rejected")], db_index=True, default="draft", max_length=16)),
                ("calculation_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("evidence_json", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, default="")),
                ("rejection_comment", models.TextField(blank=True, default="")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_me_indicator_values", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_me_indicator_values", to=settings.AUTH_USER_MODEL)),
                ("indicator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="values", to="standards.meindicator")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="submitted_me_indicator_values", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-period_end", "indicator__indicator_name"],
            },
        ),
        migrations.CreateModel(
            name="MEIndicatorValueHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=32)),
                ("from_status", models.CharField(blank=True, default="", max_length=16)),
                ("to_status", models.CharField(blank=True, default="", max_length=16)),
                ("snapshot_json", models.JSONField(blank=True, default=dict)),
                ("comment", models.TextField(blank=True, default="")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="me_indicator_value_history", to=settings.AUTH_USER_MODEL)),
                ("value", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="standards.meindicatorvalue")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meindicatorvalue",
            index=models.Index(fields=["indicator", "period_start", "period_end"], name="standards_m_indicat_98e3b2_idx"),
        ),
        migrations.AddIndex(
            model_name="meindicatorvalue",
            index=models.Index(fields=["approval_status"], name="standards_m_approva_6c3553_idx"),
        ),
        migrations.AddIndex(
            model_name="meindicatorvalue",
            index=models.Index(fields=["value_source"], name="standards_m_value_s_47cbca_idx"),
        ),
        migrations.AddIndex(
            model_name="meindicatorvaluehistory",
            index=models.Index(fields=["value", "created_at"], name="standards_m_value_i_f1bfdb_idx"),
        ),
        migrations.AddIndex(
            model_name="meindicatorvaluehistory",
            index=models.Index(fields=["action"], name="standards_m_action_001b74_idx"),
        ),
        migrations.AddConstraint(
            model_name="meindicatorvalue",
            constraint=models.UniqueConstraint(fields=("indicator", "period_start", "period_end", "value_source", "source_reference_id"), name="unique_me_indicator_value_per_source_period"),
        ),
    ]
