# Generated by Codex on 2026-06-15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0002_meindicatorvalue_meindicatorvaluehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meindicatorvalue",
            name="value_source",
            field=models.CharField(choices=[("manual", "Manual"), ("form", "Form"), ("indicator", "Indicator"), ("document", "Document"), ("external", "External"), ("import", "Import")], default="manual", max_length=16),
        ),
        migrations.CreateModel(
            name="MEIndicatorDataSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(choices=[("manual", "Manual"), ("form", "Form"), ("indicator", "Indicator"), ("document", "Document"), ("external", "External")], default="manual", max_length=16)),
                ("source_id", models.CharField(blank=True, default="", max_length=128)),
                ("calculation_method", models.CharField(choices=[("sum", "Sum"), ("count", "Count"), ("unique_count", "Unique Count"), ("average", "Average"), ("percentage", "Percentage")], max_length=16)),
                ("value_field_id", models.CharField(blank=True, default="", max_length=128)),
                ("numerator_config_json", models.JSONField(blank=True, default=dict)),
                ("denominator_config_json", models.JSONField(blank=True, default=dict)),
                ("filter_config_json", models.JSONField(blank=True, default=dict)),
                ("unicity_field_id", models.CharField(blank=True, default="", max_length=128)),
                ("period_filter_mode", models.CharField(choices=[("all_time", "All Time"), ("current_period", "Current Period"), ("custom_period", "Custom Period")], default="current_period", max_length=16)),
                ("indicator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="data_source_configs", to="standards.meindicator")),
            ],
            options={
                "ordering": ["indicator__indicator_name", "source_type", "calculation_method"],
            },
        ),
        migrations.AddIndex(
            model_name="meindicatordatasource",
            index=models.Index(fields=["indicator", "source_type"], name="standards_m_indicat_68a4ca_idx"),
        ),
        migrations.AddIndex(
            model_name="meindicatordatasource",
            index=models.Index(fields=["calculation_method"], name="standards_m_calcula_5c9f52_idx"),
        ),
        migrations.AddIndex(
            model_name="meindicatordatasource",
            index=models.Index(fields=["period_filter_mode"], name="standards_m_period__74ea41_idx"),
        ),
    ]
