# Generated by Django 4.2.30 on 2026-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0011_meindicatorvalue_override_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='indicatordisaggregatedvalue',
            new_name='standards_i_indicat_059db5_idx',
            old_name='standards_i_indicat_cda2b5_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatordisaggregatedvalue',
            new_name='standards_i_indicat_9f6a16_idx',
            old_name='standards_i_indicat_5df5ec_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatordisaggregation',
            new_name='standards_i_indicat_893fd0_idx',
            old_name='standards_i_indicat_4e4f8c_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatordisaggregation',
            new_name='standards_i_indicat_b7cdd6_idx',
            old_name='standards_i_indicat_9fb23a_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatorevidence',
            new_name='standards_i_indicat_47bba1_idx',
            old_name='standards_i_indicat_e07512_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatorevidence',
            new_name='standards_i_indicat_667c43_idx',
            old_name='standards_i_indicat_04c7f4_idx',
        ),
        migrations.RenameIndex(
            model_name='indicatorevidence',
            new_name='standards_i_evidenc_503d18_idx',
            old_name='standards_i_eviden_5c7f47_idx',
        ),
        migrations.RenameIndex(
            model_name='meindicatorcalculationlog',
            new_name='standards_m_indicat_13807f_idx',
            old_name='standards_m_indicat_a3d92e_idx',
        ),
        migrations.RenameIndex(
            model_name='meindicatorcalculationlog',
            new_name='standards_m_calcula_904dcf_idx',
            old_name='standards_m_calcula_9f0aa6_idx',
        ),
        migrations.RenameIndex(
            model_name='meindicatorcalculationlog',
            new_name='standards_m_policy__96d5ad_idx',
            old_name='standards_m_policy__4fb073_idx',
        ),
        migrations.RenameIndex(
            model_name='qualitativeindicatorconfig',
            new_name='standards_q_input_t_7e4da4_idx',
            old_name='standards_q_input_t_4d512a_idx',
        ),
        migrations.RenameIndex(
            model_name='qualitativeindicatorconfig',
            new_name='standards_q_require_60f29f_idx',
            old_name='standards_q_require_9d9fd5_idx',
        ),
        migrations.AlterField(
            model_name='establishmentcategory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='facilityrequirementrule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='foodhandlercategory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregatedvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='indicatorevidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicaltestrule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='meindicator',
            name='reporting_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual'), ('ad_hoc', 'Ad Hoc'), ('custom', 'Custom')], max_length=16),
        ),
        migrations.AlterField(
            model_name='meindicator',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='meindicatorvalue',
            name='value_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('override', 'Override'), ('import', 'Import')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='physicalexaminationrule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='qualitativeindicatorconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reportingtemplate',
            name='reporting_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual'), ('ad_hoc', 'Ad Hoc'), ('custom', 'Custom')], max_length=16),
        ),
        migrations.AlterField(
            model_name='returntoworkrule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='vaccinationrule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
    ]
