# Generated by Django 4.2.30 on 2026-06-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0012_rename_standards_i_indicat_cda2b5_idx_standards_i_indicat_059db5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='affected_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='legal_basis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='policy_category',
            field=models.CharField(blank=True, choices=[('food_handler_eligibility', 'Food Handler Eligibility Standard'), ('food_establishment_coverage', 'Food Establishment Coverage Standard'), ('medical_test', 'Medical Test Standard'), ('laboratory_investigation', 'Laboratory Investigation Standard'), ('vaccination', 'Vaccination Standard'), ('health_declaration', 'Health Declaration Standard'), ('facility_accreditation', 'Facility Accreditation Standard'), ('certificate', 'Certificate Standard'), ('reporting', 'Reporting Standard'), ('compliance_enforcement', 'Compliance and Enforcement Standard'), ('me_indicator', 'M&E Indicator Standard')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='scope',
            field=models.TextField(blank=True),
        ),
    ]
