# Generated by Django 4.2.30 on 2026-06-30 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standards', '0013_policyversion_affected_entities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Food Handler Medical Test Package', max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('package_version', models.CharField(default='1.0', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_packages', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_test_packages', to='standards.policyversion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalTestPackageComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.CharField(choices=[('health_declaration_form', 'Health Declaration Form'), ('doctor_declaration_validation', 'Doctor Declaration Validation'), ('physical_examination', 'Physical Examination'), ('vaccination_certificate_review', 'Vaccination Certificate Review'), ('stool_microscopy_culture_sensitivity', 'Stool Microscopy, Culture and Sensitivity'), ('hepatitis_a_antigen', 'Hepatitis A Antigen'), ('additional_tests', 'Additional Tests (if clinically indicated)'), ('doctor_final_review', 'Doctor Final Review'), ('certificate_of_fitness', 'Certificate of Fitness / Temporary Unfit Report'), ('other', 'Other')], max_length=48)),
                ('label', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=True)),
                ('conditional', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='standards.medicaltestpackage')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicaltestpackagecomponent',
            constraint=models.UniqueConstraint(fields=('package', 'component_type'), name='unique_component_type_per_package'),
        ),
        migrations.AddIndex(
            model_name='medicaltestpackage',
            index=models.Index(fields=['policy_version', 'status'], name='standards_m_policy__bdb5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaltestpackage',
            constraint=models.UniqueConstraint(fields=('policy_version', 'code'), name='unique_test_package_code_per_version'),
        ),
    ]
