# Generated by Django 4.2.30 on 2026-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0014_medicaltestpackage_medicaltestpackagecomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltestrule',
            name='action',
            field=models.JSONField(blank=True, default=dict, help_text='Machine-readable action, e.g. {"block_certification": true, "escalate": "doctor_review"}'),
        ),
        migrations.AddField(
            model_name='medicaltestrule',
            name='condition',
            field=models.JSONField(blank=True, default=dict, help_text='Machine-readable condition, e.g. {"field": "result", "operator": "in", "value": ["positive"]}'),
        ),
        migrations.AddField(
            model_name='medicaltestrule',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaltestrule',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=16),
        ),
    ]
