# Generated by Django 4.2.30 on 2026-07-01 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0006_seed_legacy_roles_and_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standards', '0015_medicaltestrule_action_medicaltestrule_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorAdoption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adoption_status', models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('cloned', 'Cloned'), ('declined', 'Declined'), ('superseded', 'Superseded')], db_index=True, default='adopted', max_length=16)),
                ('adopted_version', models.CharField(blank=True, default='', max_length=32)),
                ('state_target_override_enabled', models.BooleanField(default=False)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-adopted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorManualEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('federal', 'Federal'), ('state', 'State'), ('lga', 'LGA'), ('employer', 'Employer'), ('facility', 'Facility'), ('branch', 'Branch'), ('custom', 'Custom')], default='national', max_length=16)),
                ('scope_id', models.CharField(blank=True, default='', max_length=64)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('evidence_file_url', models.URLField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('review_comment', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('federal', 'Federal'), ('state', 'State'), ('lga', 'LGA'), ('employer', 'Employer'), ('facility', 'Facility'), ('branch', 'Branch'), ('custom', 'Custom')], db_index=True, default='national', max_length=16)),
                ('scope_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('target_unit', models.CharField(blank=True, default='', max_length=64)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('federal_default', 'Federal Default'), ('state_override', 'State Override'), ('lga', 'LGA'), ('organization', 'Organization'), ('custom', 'Custom')], default='federal_default', max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['indicator__indicator_name', 'scope_type', 'scope_id'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('federal', 'Federal'), ('state', 'State'), ('lga', 'LGA'), ('employer', 'Employer'), ('facility', 'Facility'), ('branch', 'Branch'), ('custom', 'Custom')], db_index=True, default='national', max_length=16)),
                ('scope_id', models.CharField(blank=True, default='', max_length=64)),
                ('band_name', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=16)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=24)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('action_recommendation', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['indicator__indicator_name', 'scope_type', 'min_value'],
            },
        ),
        migrations.AddField(
            model_name='meindicator',
            name='account_type_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='allow_state_clone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='allow_state_target_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='dashboard_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('published', 'Published'), ('active', 'Active'), ('paused', 'Paused'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_indicators', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='owner_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_indicators', to='locations.state'),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='owner_type',
            field=models.CharField(choices=[('federal', 'Federal-Owned'), ('state', 'State-Owned'), ('system', 'System Indicator'), ('employer', 'Employer-Scoped'), ('facility', 'Facility-Scoped')], db_index=True, default='federal', max_length=16),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='privacy_classification',
            field=models.CharField(blank=True, default='internal', max_length=32),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_me_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='report_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='source_indicator',
            field=models.ForeignKey(blank=True, help_text='Federal indicator this state indicator was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_indicators', to='standards.meindicator'),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_me_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=32),
        ),
        migrations.AddField(
            model_name='meindicator',
            name='visibility',
            field=models.CharField(choices=[('system_default', 'System Default'), ('federal_private', 'Federal Private'), ('federal_standard', 'Federal Standard'), ('federal_shared', 'Federal Shared'), ('state_owned', 'State Owned'), ('state_private', 'State Private'), ('organization_scoped', 'Organization Scoped'), ('role_scoped', 'Role Scoped')], db_index=True, default='federal_private', max_length=24),
        ),
        migrations.AddIndex(
            model_name='meindicator',
            index=models.Index(fields=['owner_type', 'lifecycle_status'], name='standards_m_owner_t_6f4825_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicator',
            index=models.Index(fields=['visibility'], name='standards_m_visibil_208ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='meindicator',
            index=models.Index(fields=['category'], name='standards_m_categor_f19fcf_idx'),
        ),
        migrations.AddField(
            model_name='indicatorthreshold',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='standards.meindicator'),
        ),
        migrations.AddField(
            model_name='indicatortarget',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='standards.meindicator'),
        ),
        migrations.AddField(
            model_name='indicatortarget',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_indicator_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatormanualentry',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='standards.meindicator'),
        ),
        migrations.AddField(
            model_name='indicatormanualentry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_indicator_manual_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatormanualentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_indicator_manual_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatoradoption',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_adoptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatoradoption',
            name='cloned_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clone_adoption', to='standards.meindicator'),
        ),
        migrations.AddField(
            model_name='indicatoradoption',
            name='federal_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='standards.meindicator'),
        ),
        migrations.AddField(
            model_name='indicatoradoption',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_adoptions', to='locations.state'),
        ),
        migrations.AddIndex(
            model_name='indicatorthreshold',
            index=models.Index(fields=['indicator', 'scope_type', 'scope_id'], name='standards_i_indicat_68e165_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatortarget',
            index=models.Index(fields=['indicator', 'scope_type', 'scope_id'], name='standards_i_indicat_d8386f_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatortarget',
            index=models.Index(fields=['is_active'], name='standards_i_is_acti_b7316f_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatormanualentry',
            index=models.Index(fields=['indicator', 'review_status'], name='standards_i_indicat_6e4d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatormanualentry',
            index=models.Index(fields=['period_start', 'period_end'], name='standards_i_period__a2627f_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatoradoption',
            index=models.Index(fields=['state', 'adoption_status'], name='standards_i_state_i_f9ced1_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicatoradoption',
            constraint=models.UniqueConstraint(fields=('federal_indicator', 'state'), name='unique_indicator_adoption_per_state'),
        ),
    ]
