# Generated by Django 4.2.30 on 2026-07-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0016_indicatoradoption_indicatormanualentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meindicatorvalue',
            name='performance_band',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='meindicatorvalue',
            name='performance_severity',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='meindicatorvalue',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='meindicatorvalue',
            name='variance_from_target',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
