# Generated by Django 4.2.30 on 2026-05-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='locations.lga'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('platform_operator', 'Platform Operator'), ('federal_ministry', 'Federal Ministry'), ('state_ministry', 'State Ministry'), ('employer', 'Employer'), ('medical_facility', 'Medical Facility')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['lga'], name='organizatio_lga_id_dc63fa_idx'),
        ),
    ]
