# Generated by Django 4.2.30 on 2026-05-13 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_organization_address_organization_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('directorate', 'Directorate'), ('department', 'Department'), ('unit', 'Unit'), ('branch', 'Branch'), ('lab_department', 'Lab Department'), ('clinical_department', 'Clinical Department'), ('records_department', 'Records Department'), ('other', 'Other')], db_index=True, default='unit', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_units', to='locations.lga')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organizationunit')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_units', to='locations.state')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
                'indexes': [models.Index(fields=['organization'], name='organizatio_organiz_66bc8b_idx'), models.Index(fields=['unit_type'], name='organizatio_unit_ty_d3d6d8_idx'), models.Index(fields=['parent'], name='organizatio_parent__e55a59_idx'), models.Index(fields=['state'], name='organizatio_state_i_0b6d1e_idx'), models.Index(fields=['lga'], name='organizatio_lga_id_f3aa5e_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_72681b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationunit',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_unit_name_per_organization'),
        ),
    ]
