# Generated by Django 4.2.30 on 2026-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('headquarters', 'Headquarters'), ('directorate', 'Directorate'), ('department', 'Department'), ('unit', 'Unit'), ('branch', 'Branch'), ('lab_department', 'Lab Department'), ('clinical_department', 'Clinical Department'), ('records_department', 'Records Department'), ('lga_office', 'LGA Office'), ('regional_office', 'Regional Office'), ('other', 'Other')], db_index=True, default='unit', max_length=32),
        ),
    ]
