# Generated by Django 4.2.30 on 2026-06-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_alter_organizationunit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_restricted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed'), ('expired', 'Expired'), ('pending_verification', 'Pending Verification')], db_index=True, default='active', max_length=50)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['organization__name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('organization_type', models.CharField(blank=True, choices=[('platform_operator', 'Platform Operator'), ('federal_ministry', 'Federal Ministry'), ('state_ministry', 'State Ministry'), ('employer', 'Employer'), ('medical_facility', 'Medical Facility')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=True)),
                ('is_custom_role', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated')], db_index=True, default='active', max_length=50)),
            ],
            options={
                'ordering': ['organization_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_units_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('headquarters', 'Headquarters'), ('directorate', 'Directorate'), ('department', 'Department'), ('unit', 'Unit'), ('desk', 'Desk'), ('office', 'Office'), ('branch', 'Branch'), ('regional_office', 'Regional Office'), ('site', 'Site'), ('outlet', 'Outlet'), ('store', 'Store'), ('lga_office', 'LGA Office'), ('inspectorate', 'Inspectorate'), ('lab_department', 'Lab Department'), ('clinical_department', 'Clinical Department'), ('medical_records_department', 'Medical Records Department'), ('records_department', 'Records Department'), ('finance_unit', 'Finance Unit'), ('administration_unit', 'Administration Unit'), ('support_unit', 'Support Unit'), ('technical_unit', 'Technical Unit'), ('other', 'Other')], db_index=True, default='unit', max_length=32),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent'], name='organizatio_parent__c2cd70_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['manager'], name='organizatio_manager_b5fb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['status'], name='organizatio_status_ea106a_idx'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='organizations.organizationmembership'),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='organizations.permission'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='organizatio_code_149ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='organizatio_module_d3f912_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_sensitive'], name='organizatio_is_sens_0deed2_idx'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.role'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='organizations.organizationunit'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='organizatio_role_id_e60198_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='organizatio_permiss_b5415c_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='organizatio_code_b30901_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_43ce11_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['status'], name='organizatio_status_41ceed_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system_role'], name='organizatio_is_syst_d129c0_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_custom_role'], name='organizatio_is_cust_73b166_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['membership'], name='organizatio_members_712db3_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['permission'], name='organizatio_permiss_3af6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['effect'], name='organizatio_effect_7cd3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['expires_at'], name='organizatio_expires_3221fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionoverride',
            constraint=models.UniqueConstraint(fields=('membership', 'permission'), name='unique_membership_permission_override'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user'], name='organizatio_user_id_7c4e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization'], name='organizatio_organiz_a54396_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['role'], name='organizatio_role_id_cd4208_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['unit'], name='organizatio_unit_id_384d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['status'], name='organizatio_status_3385e7_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['unit_restricted'], name='organizatio_unit_re_48df53_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'organization'), name='unique_active_membership_per_org'),
        ),
    ]
